/**
 * The five emails' words in the seven languages beside English (see
 * `emails.ts`). `{{…}}` variables are kept exactly as they are in English.
 */
import type { EmailWords } from "./emails.ts";
import type { Tag } from "./labels.ts";

/** The practice's name, address and phone: the foot of every email, in every language. */
const FOOT = "{{practice.practice_name}} · {{practice.address}} · {{practice.phone}}";

export const EMAIL_TRANSLATIONS: Record<Exclude<Tag, "en-US">, EmailWords> = {
  "de-DE": {
    confirmation: {
      name: "Terminbestätigung",
      subject: "Ihr Termin bei {{appName}} ist gebucht",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} bei {{clinician.short_name}} · {{appointment.ref}}",
      heading: "Ihr Termin steht, {{recipient.first_name}}",
      lead: "Wir haben {{appointment.minutes}} Minuten bei {{clinician.short_name}} für Sie reserviert. Kommen Sie bitte ein paar Minuten früher zur Anmeldung, dann kümmern wir uns um alles Weitere.",
      reference: "Buchungsnummer",
      clinician: "Behandler: {{clinician.name}} · {{clinician.role_label}}",
      date: "Datum: {{appointment.starts_at.date}}",
      time: "Uhrzeit: {{appointment.time_range}} ({{appointment.minutes}} Min.)",
      whatFor: "Anlass: {{visit_type.name}}",
      where: "Ort: {{practice.address}}",
      manage: "Meine Termine ansehen",
      cancel: "Bis {{practice.cancel_hours}} Stunden vorher können Sie ohne Gebühr umbuchen oder absagen.",
      fee: "Die Gebühr von {{appointment.fee}} zahlen Sie an der Anmeldung.",
      footer: FOOT,
    },
    reminder: {
      name: "Terminerinnerung",
      subject: "Bis {{appointment.starts_at.relative_day}} um {{appointment.starts_at.time}}",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "Bis {{appointment.starts_at.relative_day}} um {{appointment.starts_at.time}}",
      clinician: "Behandler: {{clinician.name}} · {{clinician.role_label}}",
      reference: "Buchungsnummer: {{appointment.ref}}",
      address: "Adresse: {{practice.address}}",
      ask: "Sie können nicht kommen?",
      cancelOnline: "Online absagen",
      toMove: "Zum Verschieben rufen Sie bitte die Anmeldung unter {{practice.phone}} an.",
      late: "Sie verspäten sich? Rufen Sie die Anmeldung unter {{practice.phone}} an.",
      footer: FOOT,
    },
    missed: {
      name: "Verpasster Termin",
      subject: "Wir haben Sie {{appointment.starts_at.relative_day}} vermisst",
      heading: "Wir haben Sie {{appointment.starts_at.relative_day}} vermisst",
      lead: "Ihr Termin um {{appointment.starts_at.time}} bei {{clinician.short_name}}. Rufen Sie die Anmeldung unter {{practice.phone}} an, dann finden wir einen neuen Termin.",
      findTime: "Termin finden",
      footer: FOOT,
    },
    recall: {
      name: "Wiedervorstellung",
      subject: "Zeit für Ihren Kontrolltermin",
      heading: "Zeit für Ihren Kontrolltermin",
      lead: "{{recall.clinician.short_name}} möchte Sie um den {{recall.due_on.day_month}} wiedersehen. Buchen Sie online einen Termin oder rufen Sie die Anmeldung an.",
      findTime: "Termin finden",
      footer: FOOT,
    },
    cancelled: {
      name: "Termin abgesagt (Schließzeit)",
      subject: "Wir mussten Ihren Termin absagen",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} bei {{clinician.short_name}}",
      heading: "Wir mussten Ihren Termin absagen",
      lead: "Es tut uns leid – die Praxis kann Sie zu diesem Zeitpunkt leider doch nicht empfangen.",
      date: "Datum: {{appointment.starts_at.date}}",
      time: "Uhrzeit: {{appointment.time_range}} ({{appointment.minutes}} Min.)",
      clinician: "Behandler: {{clinician.name}} · {{clinician.role_label}}",
      findTime: "Neuen Termin finden",
      ring: "Rufen Sie die Anmeldung unter {{practice.phone}} an.",
      footer: FOOT,
    },
  },

  "fr-FR": {
    confirmation: {
      name: "Confirmation de rendez-vous",
      subject: "Votre rendez-vous chez {{appName}} est confirmé",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} avec {{clinician.short_name}} · {{appointment.ref}}",
      heading: "Votre rendez-vous est confirmé, {{recipient.first_name}}",
      lead: "Nous avons réservé {{appointment.minutes}} minutes avec {{clinician.short_name}}. Présentez-vous à l’accueil quelques minutes en avance, nous nous occuperons du reste.",
      reference: "Référence",
      clinician: "Praticien : {{clinician.name}} · {{clinician.role_label}}",
      date: "Date : {{appointment.starts_at.date}}",
      time: "Heure : {{appointment.time_range}} ({{appointment.minutes}} min)",
      whatFor: "Motif : {{visit_type.name}}",
      where: "Adresse : {{practice.address}}",
      manage: "Voir mes rendez-vous",
      cancel: "Modification ou annulation sans frais jusqu’à {{practice.cancel_hours}} heures avant.",
      fee: "Le montant de {{appointment.fee}} est à régler à l’accueil.",
      footer: FOOT,
    },
    reminder: {
      name: "Rappel de rendez-vous",
      subject: "Rendez-vous {{appointment.starts_at.relative_day}} à {{appointment.starts_at.time}}",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "Rendez-vous {{appointment.starts_at.relative_day}} à {{appointment.starts_at.time}}",
      clinician: "Praticien : {{clinician.name}} · {{clinician.role_label}}",
      reference: "Référence : {{appointment.ref}}",
      address: "Adresse : {{practice.address}}",
      ask: "Vous ne pouvez pas venir ?",
      cancelOnline: "Annuler en ligne",
      toMove: "Pour le déplacer, appelez l’accueil au {{practice.phone}}.",
      late: "Vous êtes en retard ? Appelez l’accueil au {{practice.phone}}.",
      footer: FOOT,
    },
    missed: {
      name: "Rendez-vous manqué",
      subject: "Nous vous attendions {{appointment.starts_at.relative_day}}",
      heading: "Nous vous attendions {{appointment.starts_at.relative_day}}",
      lead: "Votre rendez-vous de {{appointment.starts_at.time}} avec {{clinician.short_name}}. Appelez l’accueil au {{practice.phone}} et nous trouverons un autre créneau.",
      findTime: "Trouver un créneau",
      footer: FOOT,
    },
    recall: {
      name: "Rappel de suivi",
      subject: "C’est le moment de votre visite de contrôle",
      heading: "C’est le moment de votre visite de contrôle",
      lead: "{{recall.clinician.short_name}} souhaite vous revoir vers le {{recall.due_on.day_month}}. Trouvez un créneau en ligne ou appelez l’accueil.",
      findTime: "Trouver un créneau",
      footer: FOOT,
    },
    cancelled: {
      name: "Rendez-vous annulé (fermeture)",
      subject: "Nous avons dû annuler votre rendez-vous",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} avec {{clinician.short_name}}",
      heading: "Nous avons dû annuler votre rendez-vous",
      lead: "Nous sommes désolés : le cabinet ne pourra finalement pas vous recevoir à ce moment-là.",
      date: "Date : {{appointment.starts_at.date}}",
      time: "Heure : {{appointment.time_range}} ({{appointment.minutes}} min)",
      clinician: "Praticien : {{clinician.name}} · {{clinician.role_label}}",
      findTime: "Trouver un nouveau créneau",
      ring: "Appelez l’accueil au {{practice.phone}}.",
      footer: FOOT,
    },
  },

  "da-DK": {
    confirmation: {
      name: "Bekræftelse af aftale",
      subject: "Du er booket ind hos {{appName}}",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} hos {{clinician.short_name}} · {{appointment.ref}}",
      heading: "Du er booket ind, {{recipient.first_name}}",
      lead: "Vi har sat {{appointment.minutes}} minutter af hos {{clinician.short_name}}. Kom til receptionen et par minutter før, så klarer vi resten.",
      reference: "Bookingnummer",
      clinician: "Behandler: {{clinician.name}} · {{clinician.role_label}}",
      date: "Dato: {{appointment.starts_at.date}}",
      time: "Tid: {{appointment.time_range}} ({{appointment.minutes}} min.)",
      whatFor: "Formål: {{visit_type.name}}",
      where: "Sted: {{practice.address}}",
      manage: "Se mine aftaler",
      cancel: "Du kan ændre eller aflyse uden gebyr indtil {{practice.cancel_hours}} timer før.",
      fee: "{{appointment.fee}} betales i receptionen.",
      footer: FOOT,
    },
    reminder: {
      name: "Påmindelse om aftale",
      subject: "Vi ses {{appointment.starts_at.relative_day}} kl. {{appointment.starts_at.time}}",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "Vi ses {{appointment.starts_at.relative_day}} kl. {{appointment.starts_at.time}}",
      clinician: "Behandler: {{clinician.name}} · {{clinician.role_label}}",
      reference: "Bookingnummer: {{appointment.ref}}",
      address: "Adresse: {{practice.address}}",
      ask: "Kan du ikke komme?",
      cancelOnline: "Aflys online",
      toMove: "Ring til receptionen på {{practice.phone}} for at flytte den.",
      late: "Er du forsinket? Ring til receptionen på {{practice.phone}}.",
      footer: FOOT,
    },
    missed: {
      name: "Udeblivelse",
      subject: "Vi savnede dig {{appointment.starts_at.relative_day}}",
      heading: "Vi savnede dig {{appointment.starts_at.relative_day}}",
      lead: "Din tid kl. {{appointment.starts_at.time}} hos {{clinician.short_name}}. Ring til receptionen på {{practice.phone}}, så finder vi en ny tid.",
      findTime: "Find en tid",
      footer: FOOT,
    },
    recall: {
      name: "Genindkaldelse",
      subject: "Tid til din kontrol",
      heading: "Tid til din kontrol",
      lead: "{{recall.clinician.short_name}} vil gerne se dig igen omkring {{recall.due_on.day_month}}. Find en tid online, eller ring til receptionen.",
      findTime: "Find en tid",
      footer: FOOT,
    },
    cancelled: {
      name: "Aflyst aftale (lukkedag)",
      subject: "Vi har måttet aflyse din aftale",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} hos {{clinician.short_name}}",
      heading: "Vi har måttet aflyse din aftale",
      lead: "Vi beklager – klinikken kan alligevel ikke tage imod dig på det tidspunkt.",
      date: "Dato: {{appointment.starts_at.date}}",
      time: "Tid: {{appointment.time_range}} ({{appointment.minutes}} min.)",
      clinician: "Behandler: {{clinician.name}} · {{clinician.role_label}}",
      findTime: "Find en ny tid",
      ring: "Ring til receptionen på {{practice.phone}}.",
      footer: FOOT,
    },
  },

  "cs-CZ": {
    confirmation: {
      name: "Potvrzení termínu",
      subject: "{{appName}}: váš termín je potvrzen",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} · {{clinician.short_name}} · {{appointment.ref}}",
      heading: "Váš termín je potvrzen, {{recipient.first_name}}",
      lead: "Rezervovali jsme pro vás {{appointment.minutes}} minut ({{clinician.short_name}}). Přijďte na recepci o pár minut dříve a o vše ostatní se postaráme.",
      reference: "Číslo rezervace",
      clinician: "Zdravotník: {{clinician.name}} · {{clinician.role_label}}",
      date: "Datum: {{appointment.starts_at.date}}",
      time: "Čas: {{appointment.time_range}} ({{appointment.minutes}} min)",
      whatFor: "Typ návštěvy: {{visit_type.name}}",
      where: "Místo: {{practice.address}}",
      manage: "Zobrazit moje termíny",
      cancel: "Termín můžete bez poplatku změnit nebo zrušit nejpozději {{practice.cancel_hours}} hodin předem.",
      fee: "Částku {{appointment.fee}} uhradíte na recepci.",
      footer: FOOT,
    },
    reminder: {
      name: "Připomínka termínu",
      subject: "Připomínáme váš termín: {{appointment.starts_at.relative_day}} v {{appointment.starts_at.time}}",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "Připomínáme váš termín: {{appointment.starts_at.relative_day}} v {{appointment.starts_at.time}}",
      clinician: "Zdravotník: {{clinician.name}} · {{clinician.role_label}}",
      reference: "Číslo rezervace: {{appointment.ref}}",
      address: "Adresa: {{practice.address}}",
      ask: "Nemůžete přijít?",
      cancelOnline: "Zrušit online",
      toMove: "Pokud ho chcete přesunout, zavolejte na recepci na číslo {{practice.phone}}.",
      late: "Máte zpoždění? Zavolejte na recepci na číslo {{practice.phone}}.",
      footer: FOOT,
    },
    missed: {
      name: "Zmeškaná návštěva",
      subject: "Čekali jsme na vás {{appointment.starts_at.relative_day}}",
      heading: "Čekali jsme na vás {{appointment.starts_at.relative_day}}",
      lead: "Váš termín v {{appointment.starts_at.time}} ({{clinician.short_name}}). Zavolejte na recepci na číslo {{practice.phone}} a najdeme jiný termín.",
      findTime: "Najít termín",
      footer: FOOT,
    },
    recall: {
      name: "Pozvánka na kontrolu",
      subject: "Je čas na kontrolu",
      heading: "Je čas na kontrolu",
      lead: "{{recall.clinician.short_name}} doporučuje další návštěvu kolem {{recall.due_on.day_month}}. Najděte si termín online nebo zavolejte na recepci.",
      findTime: "Najít termín",
      footer: FOOT,
    },
    cancelled: {
      name: "Zrušená návštěva (uzavření)",
      subject: "Váš termín jsme museli zrušit",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} · {{clinician.short_name}}",
      heading: "Váš termín jsme museli zrušit",
      lead: "Omlouváme se – ordinace vás v tuto dobu nakonec nemůže přijmout.",
      date: "Datum: {{appointment.starts_at.date}}",
      time: "Čas: {{appointment.time_range}} ({{appointment.minutes}} min)",
      clinician: "Zdravotník: {{clinician.name}} · {{clinician.role_label}}",
      findTime: "Najít nový termín",
      ring: "Zavolejte na recepci na číslo {{practice.phone}}.",
      footer: FOOT,
    },
  },

  "ar-EG": {
    confirmation: {
      name: "تأكيد الموعد",
      subject: "تم تأكيد حجزكم لدى {{appName}}",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} مع {{clinician.short_name}} · {{appointment.ref}}",
      heading: "تم تأكيد حجزكم، {{recipient.first_name}}",
      lead: "حجزنا لكم {{appointment.minutes}} دقيقة مع {{clinician.short_name}}. يُرجى الحضور إلى الاستقبال قبل الموعد ببضع دقائق، وسنتولّى الباقي.",
      reference: "رقم الحجز",
      clinician: "مقدّم الرعاية: {{clinician.name}} · {{clinician.role_label}}",
      date: "التاريخ: {{appointment.starts_at.date}}",
      time: "الوقت: {{appointment.time_range}} ({{appointment.minutes}} دقيقة)",
      whatFor: "نوع الزيارة: {{visit_type.name}}",
      where: "المكان: {{practice.address}}",
      manage: "عرض مواعيدي",
      cancel: "يمكنكم التعديل أو الإلغاء دون أي رسوم حتى {{practice.cancel_hours}} ساعة قبل الموعد.",
      fee: "يُدفع مبلغ {{appointment.fee}} في الاستقبال.",
      footer: FOOT,
    },
    reminder: {
      name: "تذكير بالموعد",
      subject: "نراكم {{appointment.starts_at.relative_day}} الساعة {{appointment.starts_at.time}}",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "نراكم {{appointment.starts_at.relative_day}} الساعة {{appointment.starts_at.time}}",
      clinician: "مقدّم الرعاية: {{clinician.name}} · {{clinician.role_label}}",
      reference: "رقم الحجز: {{appointment.ref}}",
      address: "العنوان: {{practice.address}}",
      ask: "هل يتعذّر عليكم الحضور؟",
      cancelOnline: "الإلغاء عبر الإنترنت",
      toMove: "لتغيير الموعد، اتصلوا بالاستقبال على {{practice.phone}}.",
      late: "ستتأخرون؟ اتصلوا بالاستقبال على {{practice.phone}}.",
      footer: FOOT,
    },
    missed: {
      name: "زيارة فائتة",
      subject: "لم نركم في موعدكم {{appointment.starts_at.relative_day}}",
      heading: "لم نركم في موعدكم {{appointment.starts_at.relative_day}}",
      lead: "موعدكم الساعة {{appointment.starts_at.time}} مع {{clinician.short_name}}. اتصلوا بالاستقبال على {{practice.phone}} وسنجد لكم موعدًا آخر.",
      findTime: "البحث عن موعد",
      footer: FOOT,
    },
    recall: {
      name: "دعوة للمتابعة",
      subject: "حان موعد الفحص الدوري",
      heading: "حان موعد الفحص الدوري",
      lead: "بحسب توصية {{recall.clinician.short_name}}، حان وقت زيارتكم التالية في حدود {{recall.due_on.day_month}}. احجزوا موعدًا عبر الإنترنت أو اتصلوا بالاستقبال.",
      findTime: "البحث عن موعد",
      footer: FOOT,
    },
    cancelled: {
      name: "إلغاء زيارة (إغلاق)",
      subject: "اضطررنا إلى إلغاء زيارتكم",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} مع {{clinician.short_name}}",
      heading: "اضطررنا إلى إلغاء زيارتكم",
      lead: "نعتذر إليكم، فلن تتمكن العيادة من استقبالكم في هذا الموعد.",
      date: "التاريخ: {{appointment.starts_at.date}}",
      time: "الوقت: {{appointment.time_range}} ({{appointment.minutes}} دقيقة)",
      clinician: "مقدّم الرعاية: {{clinician.name}} · {{clinician.role_label}}",
      findTime: "البحث عن موعد جديد",
      ring: "اتصلوا بالاستقبال على {{practice.phone}}.",
      footer: FOOT,
    },
  },

  "zh-CN": {
    confirmation: {
      name: "预约确认",
      subject: "您已成功预约{{appName}}",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} · {{clinician.short_name}} · {{appointment.ref}}",
      heading: "{{recipient.first_name}}，您的预约已确认",
      lead: "我们已为您预留与{{clinician.short_name}}的{{appointment.minutes}}分钟就诊时间。请提前几分钟到前台，其余事项我们会为您安排好。",
      reference: "预约编号",
      clinician: "医护人员：{{clinician.name}} · {{clinician.role_label}}",
      date: "日期：{{appointment.starts_at.date}}",
      time: "时间：{{appointment.time_range}}（{{appointment.minutes}}分钟）",
      whatFor: "就诊类型：{{visit_type.name}}",
      where: "地点：{{practice.address}}",
      manage: "查看我的预约",
      cancel: "就诊前{{practice.cancel_hours}}小时以前更改或取消，不收取任何费用。",
      fee: "费用{{appointment.fee}}请在前台支付。",
      footer: FOOT,
    },
    reminder: {
      name: "就诊提醒",
      subject: "期待{{appointment.starts_at.relative_day}}{{appointment.starts_at.time}}与您见面",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "期待{{appointment.starts_at.relative_day}}{{appointment.starts_at.time}}与您见面",
      clinician: "医护人员：{{clinician.name}} · {{clinician.role_label}}",
      reference: "预约编号：{{appointment.ref}}",
      address: "地址：{{practice.address}}",
      ask: "无法前来？",
      cancelOnline: "在线取消",
      toMove: "如需改期，请致电前台{{practice.phone}}。",
      late: "会迟到吗？请致电前台{{practice.phone}}。",
      footer: FOOT,
    },
    missed: {
      name: "错过就诊",
      subject: "{{appointment.starts_at.relative_day}}没能见到您",
      heading: "{{appointment.starts_at.relative_day}}没能见到您",
      lead: "您与{{clinician.short_name}}的{{appointment.starts_at.time}}预约。请致电前台{{practice.phone}}，我们会为您另约时间。",
      findTime: "选择时间",
      footer: FOOT,
    },
    recall: {
      name: "复诊通知",
      subject: "是时候复查了",
      heading: "是时候复查了",
      lead: "{{recall.clinician.short_name}}希望在{{recall.due_on.day_month}}前后再次为您复诊。请在线预约或致电前台。",
      findTime: "选择时间",
      footer: FOOT,
    },
    cancelled: {
      name: "就诊取消（停诊）",
      subject: "我们不得不取消您的预约",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} · {{clinician.short_name}}",
      heading: "我们不得不取消您的预约",
      lead: "非常抱歉，诊所届时无法为您接诊。",
      date: "日期：{{appointment.starts_at.date}}",
      time: "时间：{{appointment.time_range}}（{{appointment.minutes}}分钟）",
      clinician: "医护人员：{{clinician.name}} · {{clinician.role_label}}",
      findTime: "重新选择时间",
      ring: "请致电前台{{practice.phone}}。",
      footer: FOOT,
    },
  },

  "zh-TW": {
    confirmation: {
      name: "預約確認",
      subject: "您已成功預約{{appName}}",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} · {{clinician.short_name}} · {{appointment.ref}}",
      heading: "{{recipient.first_name}}，您的預約已確認",
      lead: "我們已為您保留與{{clinician.short_name}}的{{appointment.minutes}}分鐘看診時間。請提早幾分鐘到櫃台報到，其餘事項我們會為您安排。",
      reference: "預約編號",
      clinician: "醫護人員：{{clinician.name}} · {{clinician.role_label}}",
      date: "日期：{{appointment.starts_at.date}}",
      time: "時間：{{appointment.time_range}}（{{appointment.minutes}}分鐘）",
      whatFor: "看診類型：{{visit_type.name}}",
      where: "地點：{{practice.address}}",
      manage: "查看我的預約",
      cancel: "看診前{{practice.cancel_hours}}小時以前更改或取消，不收取任何費用。",
      fee: "費用{{appointment.fee}}請於櫃台支付。",
      footer: FOOT,
    },
    reminder: {
      name: "看診提醒",
      subject: "期待{{appointment.starts_at.relative_day}}{{appointment.starts_at.time}}與您見面",
      preheader: "{{clinician.short_name}} · {{appointment.ref}} · {{practice.address}}",
      heading: "期待{{appointment.starts_at.relative_day}}{{appointment.starts_at.time}}與您見面",
      clinician: "醫護人員：{{clinician.name}} · {{clinician.role_label}}",
      reference: "預約編號：{{appointment.ref}}",
      address: "地址：{{practice.address}}",
      ask: "無法前來嗎？",
      cancelOnline: "線上取消",
      toMove: "如需改期，請致電櫃台{{practice.phone}}。",
      late: "會遲到嗎？請致電櫃台{{practice.phone}}。",
      footer: FOOT,
    },
    missed: {
      name: "錯過看診",
      subject: "{{appointment.starts_at.relative_day}}沒能見到您",
      heading: "{{appointment.starts_at.relative_day}}沒能見到您",
      lead: "您與{{clinician.short_name}}的{{appointment.starts_at.time}}預約。請致電櫃台{{practice.phone}}，我們會為您另約時間。",
      findTime: "選擇時間",
      footer: FOOT,
    },
    recall: {
      name: "回診通知",
      subject: "該回診檢查了",
      heading: "該回診檢查了",
      lead: "{{recall.clinician.short_name}}希望在{{recall.due_on.day_month}}前後再次為您看診。請線上預約或致電櫃台。",
      findTime: "選擇時間",
      footer: FOOT,
    },
    cancelled: {
      name: "看診取消（休診）",
      subject: "我們不得不取消您的預約",
      preheader: "{{appointment.starts_at.date}} · {{appointment.starts_at.time}} · {{clinician.short_name}}",
      heading: "我們不得不取消您的預約",
      lead: "非常抱歉，診所屆時無法為您看診。",
      date: "日期：{{appointment.starts_at.date}}",
      time: "時間：{{appointment.time_range}}（{{appointment.minutes}}分鐘）",
      clinician: "醫護人員：{{clinician.name}} · {{clinician.role_label}}",
      findTime: "重新選擇時間",
      ring: "請致電櫃台{{practice.phone}}。",
      footer: FOOT,
    },
  },
};
