/**
 * The manifest's words in the seven languages beside English, keyed by the
 * English (see `labels.ts`). Every label the manifest shows is here.
 */
import type { Translation } from "./labels.ts";

export const WORDS: Record<string, Translation> = {
  // ── tables (a row's name, then the list's) ─────────────────────────────────
  "Practice settings": { "de-DE": "Praxiseinstellungen", "fr-FR": "Paramètres du cabinet", "da-DK": "Klinikindstillinger", "cs-CZ": "Nastavení ordinace", "ar-EG": "إعدادات العيادة", "zh-CN": "诊所设置", "zh-TW": "診所設定" },
  "Opening hours": { "de-DE": "Öffnungszeiten", "fr-FR": "Horaires d’ouverture", "da-DK": "Åbningstider", "cs-CZ": "Ordinační hodiny", "ar-EG": "مواعيد العمل", "zh-CN": "门诊时间", "zh-TW": "門診時間" },
  "Clinician": { "de-DE": "Behandler", "fr-FR": "Praticien", "da-DK": "Behandler", "cs-CZ": "Zdravotník", "ar-EG": "مقدّم الرعاية", "zh-CN": "医护人员", "zh-TW": "醫護人員" },
  "Clinicians": { "de-DE": "Behandler", "fr-FR": "Praticiens", "da-DK": "Behandlere", "cs-CZ": "Zdravotníci", "ar-EG": "مقدّمو الرعاية", "zh-CN": "医护人员", "zh-TW": "醫護人員" },
  "Visit type": { "de-DE": "Terminart", "fr-FR": "Type de consultation", "da-DK": "Konsultationstype", "cs-CZ": "Typ návštěvy", "ar-EG": "نوع الزيارة", "zh-CN": "就诊类型", "zh-TW": "看診類型" },
  "Visit types": { "de-DE": "Terminarten", "fr-FR": "Types de consultation", "da-DK": "Konsultationstyper", "cs-CZ": "Typy návštěv", "ar-EG": "أنواع الزيارات", "zh-CN": "就诊类型", "zh-TW": "看診類型" },
  "Visit a clinician does": { "de-DE": "Terminart eines Behandlers", "fr-FR": "Consultation assurée par un praticien", "da-DK": "Konsultationstype hos en behandler", "cs-CZ": "Typ návštěvy zdravotníka", "ar-EG": "زيارة يقدّمها مقدّم الرعاية", "zh-CN": "医护人员的就诊类型", "zh-TW": "醫護人員的看診類型" },
  "Visits clinicians do": { "de-DE": "Terminarten der Behandler", "fr-FR": "Consultations assurées par les praticiens", "da-DK": "Konsultationstyper hos behandlerne", "cs-CZ": "Typy návštěv zdravotníků", "ar-EG": "زيارات يقدّمها مقدّمو الرعاية", "zh-CN": "医护人员的就诊类型", "zh-TW": "醫護人員的看診類型" },
  "Clinician's hours": { "de-DE": "Sprechzeiten des Behandlers", "fr-FR": "Horaires du praticien", "da-DK": "Behandlerens arbejdstider", "cs-CZ": "Pracovní doba zdravotníka", "ar-EG": "ساعات عمل مقدّم الرعاية", "zh-CN": "医护人员出诊时间", "zh-TW": "醫護人員看診時間" },
  "Clinicians' hours": { "de-DE": "Sprechzeiten der Behandler", "fr-FR": "Horaires des praticiens", "da-DK": "Behandlernes arbejdstider", "cs-CZ": "Pracovní doba zdravotníků", "ar-EG": "ساعات عمل مقدّمي الرعاية", "zh-CN": "医护人员出诊时间", "zh-TW": "醫護人員看診時間" },
  "Closure": { "de-DE": "Schließzeit", "fr-FR": "Fermeture", "da-DK": "Lukkedag", "cs-CZ": "Uzavření", "ar-EG": "إغلاق", "zh-CN": "停诊", "zh-TW": "休診" },
  "Closures": { "de-DE": "Schließzeiten", "fr-FR": "Fermetures", "da-DK": "Lukkedage", "cs-CZ": "Uzavření ordinace", "ar-EG": "أيام الإغلاق", "zh-CN": "停诊安排", "zh-TW": "休診安排" },
  "Question": { "de-DE": "Frage", "fr-FR": "Question", "da-DK": "Spørgsmål", "cs-CZ": "Otázka", "ar-EG": "السؤال", "zh-CN": "问题", "zh-TW": "問題" },
  "Questions": { "de-DE": "Fragen", "fr-FR": "Questions", "da-DK": "Spørgsmål", "cs-CZ": "Otázky", "ar-EG": "الأسئلة", "zh-CN": "常见问题", "zh-TW": "常見問題" },
  "Patient": { "de-DE": "Patient", "fr-FR": "Patient", "da-DK": "Patient", "cs-CZ": "Pacient", "ar-EG": "المريض", "zh-CN": "患者", "zh-TW": "病患" },
  "Patients": { "de-DE": "Patienten", "fr-FR": "Patients", "da-DK": "Patienter", "cs-CZ": "Pacienti", "ar-EG": "المرضى", "zh-CN": "患者", "zh-TW": "病患" },
  "Registration": { "de-DE": "Anmeldung", "fr-FR": "Inscription", "da-DK": "Tilmelding", "cs-CZ": "Registrace", "ar-EG": "طلب التسجيل", "zh-CN": "登记", "zh-TW": "登記" },
  "Registrations": { "de-DE": "Anmeldungen", "fr-FR": "Inscriptions", "da-DK": "Tilmeldinger", "cs-CZ": "Registrace", "ar-EG": "طلبات التسجيل", "zh-CN": "登记", "zh-TW": "登記" },
  "Appointment": { "de-DE": "Termin", "fr-FR": "Rendez-vous", "da-DK": "Aftale", "cs-CZ": "Termín", "ar-EG": "الموعد", "zh-CN": "预约", "zh-TW": "預約" },
  "Appointments": { "de-DE": "Termine", "fr-FR": "Rendez-vous", "da-DK": "Aftaler", "cs-CZ": "Termíny", "ar-EG": "المواعيد", "zh-CN": "预约", "zh-TW": "預約" },
  "Payment": { "de-DE": "Zahlung", "fr-FR": "Paiement", "da-DK": "Betaling", "cs-CZ": "Platba", "ar-EG": "دفعة", "zh-CN": "付款", "zh-TW": "付款" },
  "Payments": { "de-DE": "Zahlungen", "fr-FR": "Paiements", "da-DK": "Betalinger", "cs-CZ": "Platby", "ar-EG": "المدفوعات", "zh-CN": "付款记录", "zh-TW": "付款紀錄" },
  "Write-off": { "de-DE": "Abschreibung", "fr-FR": "Remise", "da-DK": "Afskrivning", "cs-CZ": "Odpis", "ar-EG": "إعفاء", "zh-CN": "减免", "zh-TW": "減免" },
  "Write-offs": { "de-DE": "Abschreibungen", "fr-FR": "Remises", "da-DK": "Afskrivninger", "cs-CZ": "Odpisy", "ar-EG": "الإعفاءات", "zh-CN": "减免记录", "zh-TW": "減免紀錄" },
  "Note": { "de-DE": "Notiz", "fr-FR": "Note", "da-DK": "Note", "cs-CZ": "Poznámka", "ar-EG": "ملاحظة", "zh-CN": "备注", "zh-TW": "備註" },
  "Notes": { "de-DE": "Notizen", "fr-FR": "Notes", "da-DK": "Noter", "cs-CZ": "Poznámky", "ar-EG": "ملاحظات", "zh-CN": "备注", "zh-TW": "備註" },
  "Recall": { "de-DE": "Wiedervorstellung", "fr-FR": "Rappel de suivi", "da-DK": "Genindkaldelse", "cs-CZ": "Pozvánka na kontrolu", "ar-EG": "دعوة للمتابعة", "zh-CN": "复诊通知", "zh-TW": "回診通知" },
  "Recalls": { "de-DE": "Wiedervorstellungen", "fr-FR": "Rappels de suivi", "da-DK": "Genindkaldelser", "cs-CZ": "Pozvánky na kontrolu", "ar-EG": "دعوات المتابعة", "zh-CN": "复诊通知", "zh-TW": "回診通知" },
  "Waiting-list entry": { "de-DE": "Wartelisteneintrag", "fr-FR": "Inscription en liste d’attente", "da-DK": "Plads på ventelisten", "cs-CZ": "Záznam na čekací listině", "ar-EG": "إدراج في قائمة الانتظار", "zh-CN": "候补登记", "zh-TW": "候補登記" },
  "Waiting list": { "de-DE": "Warteliste", "fr-FR": "Liste d’attente", "da-DK": "Venteliste", "cs-CZ": "Čekací listina", "ar-EG": "قائمة الانتظار", "zh-CN": "候补名单", "zh-TW": "候補名單" },
  "Message": { "de-DE": "Nachricht", "fr-FR": "Message", "da-DK": "Besked", "cs-CZ": "Zpráva", "ar-EG": "الرسالة", "zh-CN": "邮件", "zh-TW": "郵件" },
  "Messages": { "de-DE": "Nachrichten", "fr-FR": "Messages", "da-DK": "Beskeder", "cs-CZ": "Zprávy", "ar-EG": "الرسائل", "zh-CN": "邮件", "zh-TW": "郵件" },
  "Day close": { "de-DE": "Tagesabschluss", "fr-FR": "Clôture de journée", "da-DK": "Dagsafslutning", "cs-CZ": "Uzávěrka dne", "ar-EG": "إقفال اليوم", "zh-CN": "日结", "zh-TW": "日結" },
  "Day closes": { "de-DE": "Tagesabschlüsse", "fr-FR": "Clôtures de journée", "da-DK": "Dagsafslutninger", "cs-CZ": "Uzávěrky dne", "ar-EG": "سجل إقفال الأيام", "zh-CN": "日结记录", "zh-TW": "日結紀錄" },

  // ── pages and nav groups ───────────────────────────────────────────────────
  "Overview": { "de-DE": "Übersicht", "fr-FR": "Vue d’ensemble", "da-DK": "Overblik", "cs-CZ": "Přehled", "ar-EG": "نظرة عامة", "zh-CN": "概览", "zh-TW": "總覽" },
  "Visits": { "de-DE": "Besuche", "fr-FR": "Consultations", "da-DK": "Besøg", "cs-CZ": "Návštěvy", "ar-EG": "الزيارات", "zh-CN": "就诊", "zh-TW": "看診" },
  "Records": { "de-DE": "Aufzeichnungen", "fr-FR": "Registres", "da-DK": "Registreringer", "cs-CZ": "Záznamy", "ar-EG": "السجلات", "zh-CN": "记录", "zh-TW": "記錄" },
  "Manage": { "de-DE": "Verwalten", "fr-FR": "Gérer", "da-DK": "Administrer", "cs-CZ": "Správa", "ar-EG": "الإدارة", "zh-CN": "管理", "zh-TW": "管理" },

  // ── column labels: the practice's settings ─────────────────────────────────
  "Practice name": { "de-DE": "Name der Praxis", "fr-FR": "Nom du cabinet", "da-DK": "Klinikkens navn", "cs-CZ": "Název ordinace", "ar-EG": "اسم العيادة", "zh-CN": "诊所名称", "zh-TW": "診所名稱" },
  "Letters on the tile": { "de-DE": "Buchstaben auf der Kachel", "fr-FR": "Lettres sur la vignette", "da-DK": "Bogstaver på ikonet", "cs-CZ": "Písmena na dlaždici", "ar-EG": "الأحرف على الأيقونة", "zh-CN": "图标字母", "zh-TW": "圖示字母" },
  "Address": { "de-DE": "Adresse", "fr-FR": "Adresse", "da-DK": "Adresse", "cs-CZ": "Adresa", "ar-EG": "العنوان", "zh-CN": "地址", "zh-TW": "地址" },
  "Desk phone": { "de-DE": "Telefon der Anmeldung", "fr-FR": "Téléphone de l’accueil", "da-DK": "Receptionens telefon", "cs-CZ": "Telefon recepce", "ar-EG": "هاتف الاستقبال", "zh-CN": "前台电话", "zh-TW": "櫃台電話" },
  "Desk email": { "de-DE": "E-Mail der Anmeldung", "fr-FR": "E-mail de l’accueil", "da-DK": "Receptionens e-mail", "cs-CZ": "E-mail recepce", "ar-EG": "بريد الاستقبال الإلكتروني", "zh-CN": "前台邮箱", "zh-TW": "櫃台電子郵件" },
  "A line about the practice": { "de-DE": "Ein Satz über die Praxis", "fr-FR": "Une phrase sur le cabinet", "da-DK": "En linje om klinikken", "cs-CZ": "Pár slov o ordinaci", "ar-EG": "سطر عن العيادة", "zh-CN": "诊所简介", "zh-TW": "診所簡介" },
  "Directions": { "de-DE": "Anfahrt", "fr-FR": "Accès", "da-DK": "Vejvisning", "cs-CZ": "Jak k nám", "ar-EG": "كيفية الوصول", "zh-CN": "交通指引", "zh-TW": "交通指引" },
  "Map link": { "de-DE": "Link zur Karte", "fr-FR": "Lien vers la carte", "da-DK": "Link til kort", "cs-CZ": "Odkaz na mapu", "ar-EG": "رابط الخريطة", "zh-CN": "地图链接", "zh-TW": "地圖連結" },
  "Photo of the entrance": { "de-DE": "Foto vom Eingang", "fr-FR": "Photo de l’entrée", "da-DK": "Foto af indgangen", "cs-CZ": "Fotka vchodu", "ar-EG": "صورة المدخل", "zh-CN": "入口照片", "zh-TW": "入口照片" },
  "How to pay": { "de-DE": "So bezahlen Sie", "fr-FR": "Comment payer", "da-DK": "Sådan betaler du", "cs-CZ": "Jak zaplatit", "ar-EG": "طريقة السداد", "zh-CN": "付款说明", "zh-TW": "付款說明" },
  "Paying through an insurer": { "de-DE": "Zahlung über die Versicherung", "fr-FR": "Paiement par une assurance", "da-DK": "Betaling via forsikring", "cs-CZ": "Platba přes pojišťovnu", "ar-EG": "الدفع عبر شركة التأمين", "zh-CN": "通过保险支付", "zh-TW": "透過保險支付" },
  "Privacy notice link": { "de-DE": "Link zur Datenschutzerklärung", "fr-FR": "Lien vers la politique de confidentialité", "da-DK": "Link til privatlivspolitik", "cs-CZ": "Odkaz na zásady ochrany osobních údajů", "ar-EG": "رابط إشعار الخصوصية", "zh-CN": "隐私声明链接", "zh-TW": "隱私權聲明連結" },
  "Currency": { "de-DE": "Währung", "fr-FR": "Devise", "da-DK": "Valuta", "cs-CZ": "Měna", "ar-EG": "العملة", "zh-CN": "货币", "zh-TW": "貨幣" },
  "Language": { "de-DE": "Sprache", "fr-FR": "Langue", "da-DK": "Sprog", "cs-CZ": "Jazyk", "ar-EG": "اللغة", "zh-CN": "语言", "zh-TW": "語言" },
  "Booking grid (minutes)": { "de-DE": "Buchungsraster (Minuten)", "fr-FR": "Grille de réservation (minutes)", "da-DK": "Bookinginterval (minutter)", "cs-CZ": "Rastr objednávek (minuty)", "ar-EG": "فاصل الحجز (بالدقائق)", "zh-CN": "预约时间间隔（分钟）", "zh-TW": "預約時段間隔（分鐘）" },
  "Days open for booking": { "de-DE": "Tage im Voraus buchbar", "fr-FR": "Jours ouverts à la réservation", "da-DK": "Dage åbne for booking", "cs-CZ": "Dny otevřené k objednání", "ar-EG": "عدد الأيام المتاحة للحجز", "zh-CN": "可预约天数", "zh-TW": "可預約天數" },
  "Shortest notice online (minutes)": { "de-DE": "Kürzeste Vorlaufzeit online (Minuten)", "fr-FR": "Délai minimum en ligne (minutes)", "da-DK": "Korteste varsel online (minutter)", "cs-CZ": "Nejkratší předstih online (minuty)", "ar-EG": "أقصر مهلة للحجز عبر الإنترنت (بالدقائق)", "zh-CN": "在线预约最短提前时间（分钟）", "zh-TW": "線上預約最短提前時間（分鐘）" },
  "New patients may book online": { "de-DE": "Neue Patienten können online buchen", "fr-FR": "Les nouveaux patients peuvent réserver en ligne", "da-DK": "Nye patienter kan booke online", "cs-CZ": "Noví pacienti se mohou objednat online", "ar-EG": "يمكن للمرضى الجدد الحجز عبر الإنترنت", "zh-CN": "新患者可在线预约", "zh-TW": "新病患可線上預約" },
  "Online booking": { "de-DE": "Online-Buchung", "fr-FR": "Réservation en ligne", "da-DK": "Onlinebooking", "cs-CZ": "Objednávání online", "ar-EG": "الحجز عبر الإنترنت", "zh-CN": "在线预约", "zh-TW": "線上預約" },
  "No-show after (minutes)": { "de-DE": "Nicht erschienen nach (Minuten)", "fr-FR": "Absent après (minutes)", "da-DK": "Udeblevet efter (minutter)", "cs-CZ": "Nedostavení po (minutách)", "ar-EG": "يُعدّ غائبًا بعد (بالدقائق)", "zh-CN": "超时未到判定（分钟）", "zh-TW": "逾時未到判定（分鐘）" },
  "Cancellation window (hours before)": { "de-DE": "Absagefrist (Stunden vorher)", "fr-FR": "Délai d’annulation (heures avant)", "da-DK": "Afbudsfrist (timer før)", "cs-CZ": "Lhůta pro zrušení (hodin předem)", "ar-EG": "مهلة الإلغاء (ساعات قبل الموعد)", "zh-CN": "取消期限（提前小时数）", "zh-TW": "取消期限（提前小時數）" },
  "Send reminders": { "de-DE": "Erinnerungen senden", "fr-FR": "Envoyer des rappels", "da-DK": "Send påmindelser", "cs-CZ": "Posílat připomínky", "ar-EG": "إرسال التذكيرات", "zh-CN": "发送提醒", "zh-TW": "寄送提醒" },
  "Remind (hours before)": { "de-DE": "Erinnern (Stunden vorher)", "fr-FR": "Rappel (heures avant)", "da-DK": "Påmind (timer før)", "cs-CZ": "Připomenout (hodin předem)", "ar-EG": "التذكير (ساعات قبل الموعد)", "zh-CN": "提前提醒（小时）", "zh-TW": "提前提醒（小時）" },
  "Arrivals kiosk": { "de-DE": "Check-in-Terminal", "fr-FR": "Borne d’accueil", "da-DK": "Ankomstskærm", "cs-CZ": "Kiosek pro příchody", "ar-EG": "جهاز تسجيل الوصول", "zh-CN": "自助签到机", "zh-TW": "自助報到機" },

  // ── column labels: hours and closures ──────────────────────────────────────
  "Weekday": { "de-DE": "Wochentag", "fr-FR": "Jour de la semaine", "da-DK": "Ugedag", "cs-CZ": "Den v týdnu", "ar-EG": "يوم الأسبوع", "zh-CN": "星期", "zh-TW": "星期" },
  "Open": { "de-DE": "Geöffnet", "fr-FR": "Ouvert", "da-DK": "Åben", "cs-CZ": "Otevřeno", "ar-EG": "مفتوح", "zh-CN": "营业", "zh-TW": "營業" },
  "Opens": { "de-DE": "Öffnet", "fr-FR": "Ouverture", "da-DK": "Åbner", "cs-CZ": "Otevírá", "ar-EG": "وقت الفتح", "zh-CN": "开门时间", "zh-TW": "開門時間" },
  "Closes": { "de-DE": "Schließt", "fr-FR": "Fermeture", "da-DK": "Lukker", "cs-CZ": "Zavírá", "ar-EG": "وقت الإغلاق", "zh-CN": "关门时间", "zh-TW": "關門時間" },
  "Desk closed from": { "de-DE": "Anmeldung geschlossen von", "fr-FR": "Accueil fermé de", "da-DK": "Receptionen lukket fra", "cs-CZ": "Recepce zavřená od", "ar-EG": "الاستقبال مغلق من", "zh-CN": "前台休息开始", "zh-TW": "櫃台休息開始" },
  "Desk closed until": { "de-DE": "Anmeldung geschlossen bis", "fr-FR": "Accueil fermé jusqu’à", "da-DK": "Receptionen lukket til", "cs-CZ": "Recepce zavřená do", "ar-EG": "الاستقبال مغلق حتى", "zh-CN": "前台休息结束", "zh-TW": "櫃台休息結束" },
  "Starts": { "de-DE": "Beginn", "fr-FR": "Début", "da-DK": "Start", "cs-CZ": "Začátek", "ar-EG": "البداية", "zh-CN": "开始时间", "zh-TW": "開始時間" },
  "Finishes": { "de-DE": "Ende", "fr-FR": "Fin", "da-DK": "Slut", "cs-CZ": "Konec", "ar-EG": "النهاية", "zh-CN": "结束时间", "zh-TW": "結束時間" },
  "Break from": { "de-DE": "Pause von", "fr-FR": "Pause de", "da-DK": "Pause fra", "cs-CZ": "Přestávka od", "ar-EG": "الاستراحة من", "zh-CN": "休息开始", "zh-TW": "休息開始" },
  "Break until": { "de-DE": "Pause bis", "fr-FR": "Pause jusqu’à", "da-DK": "Pause til", "cs-CZ": "Přestávka do", "ar-EG": "الاستراحة حتى", "zh-CN": "休息结束", "zh-TW": "休息結束" },
  "Who is away (empty: the whole practice)": { "de-DE": "Wer fehlt (leer: die ganze Praxis)", "fr-FR": "Qui est absent (vide : tout le cabinet)", "da-DK": "Hvem er væk (tom: hele klinikken)", "cs-CZ": "Kdo chybí (prázdné: celá ordinace)", "ar-EG": "مَن الغائب (فارغ: العيادة كلها)", "zh-CN": "停诊人员（留空：整个诊所）", "zh-TW": "休診人員（留空：整間診所）" },
  "From": { "de-DE": "Von", "fr-FR": "Du", "da-DK": "Fra", "cs-CZ": "Od", "ar-EG": "من", "zh-CN": "开始日期", "zh-TW": "開始日期" },
  "To": { "de-DE": "Bis", "fr-FR": "Au", "da-DK": "Til", "cs-CZ": "Do", "ar-EG": "إلى", "zh-CN": "结束日期", "zh-TW": "結束日期" },
  "Label": { "de-DE": "Bezeichnung", "fr-FR": "Libellé", "da-DK": "Betegnelse", "cs-CZ": "Název", "ar-EG": "التسمية", "zh-CN": "名称", "zh-TW": "名稱" },
  "A note for patients": { "de-DE": "Hinweis für Patienten", "fr-FR": "Un mot pour les patients", "da-DK": "En besked til patienterne", "cs-CZ": "Vzkaz pro pacienty", "ar-EG": "ملاحظة للمرضى", "zh-CN": "给患者的说明", "zh-TW": "給病患的說明" },
  "Closed": { "de-DE": "Geschlossen", "fr-FR": "Fermé", "da-DK": "Lukket", "cs-CZ": "Zavřeno", "ar-EG": "مغلق", "zh-CN": "停诊", "zh-TW": "休診" },

  // ── column labels: clinicians, visit types, questions ──────────────────────
  "Name": { "de-DE": "Name", "fr-FR": "Nom", "da-DK": "Navn", "cs-CZ": "Jméno", "ar-EG": "الاسم", "zh-CN": "姓名", "zh-TW": "姓名" },
  "Short name": { "de-DE": "Kurzname", "fr-FR": "Nom court", "da-DK": "Kort navn", "cs-CZ": "Krátký název", "ar-EG": "الاسم المختصر", "zh-CN": "简称", "zh-TW": "簡稱" },
  "Role": { "de-DE": "Funktion", "fr-FR": "Fonction", "da-DK": "Stilling", "cs-CZ": "Profese", "ar-EG": "المسمّى الوظيفي", "zh-CN": "职称", "zh-TW": "職稱" },
  "Colour": { "de-DE": "Farbe", "fr-FR": "Couleur", "da-DK": "Farve", "cs-CZ": "Barva", "ar-EG": "اللون", "zh-CN": "颜色", "zh-TW": "顏色" },
  "Photo": { "de-DE": "Foto", "fr-FR": "Photo", "da-DK": "Foto", "cs-CZ": "Fotka", "ar-EG": "الصورة", "zh-CN": "图片", "zh-TW": "圖片" },
  "About them": { "de-DE": "Vorstellung", "fr-FR": "Présentation", "da-DK": "Præsentation", "cs-CZ": "Představení", "ar-EG": "نبذة تعريفية", "zh-CN": "个人简介", "zh-TW": "個人簡介" },
  "Bookable online": { "de-DE": "Online buchbar", "fr-FR": "Réservable en ligne", "da-DK": "Kan bookes online", "cs-CZ": "Lze objednat online", "ar-EG": "متاح للحجز عبر الإنترنت", "zh-CN": "可在线预约", "zh-TW": "可線上預約" },
  "Working here": { "de-DE": "Arbeitet hier", "fr-FR": "En poste", "da-DK": "Arbejder her", "cs-CZ": "Pracuje zde", "ar-EG": "يعمل هنا", "zh-CN": "在职", "zh-TW": "在職" },
  "Position": { "de-DE": "Reihenfolge", "fr-FR": "Ordre", "da-DK": "Rækkefølge", "cs-CZ": "Pořadí", "ar-EG": "الترتيب", "zh-CN": "排序", "zh-TW": "排序" },
  "Their sign-in email": { "de-DE": "Anmelde-E-Mail", "fr-FR": "E-mail de connexion", "da-DK": "Login-e-mail", "cs-CZ": "Přihlašovací e-mail", "ar-EG": "بريد تسجيل الدخول", "zh-CN": "登录邮箱", "zh-TW": "登入電子郵件" },
  "Length (minutes)": { "de-DE": "Dauer (Minuten)", "fr-FR": "Durée (minutes)", "da-DK": "Varighed (minutter)", "cs-CZ": "Délka (minuty)", "ar-EG": "المدة (بالدقائق)", "zh-CN": "时长（分钟）", "zh-TW": "時長（分鐘）" },
  "Fee": { "de-DE": "Gebühr", "fr-FR": "Tarif", "da-DK": "Gebyr", "cs-CZ": "Poplatek", "ar-EG": "الرسوم", "zh-CN": "费用", "zh-TW": "費用" },
  "Icon": { "de-DE": "Symbol", "fr-FR": "Icône", "da-DK": "Ikon", "cs-CZ": "Ikona", "ar-EG": "الأيقونة", "zh-CN": "图标", "zh-TW": "圖示" },
  "New patients only": { "de-DE": "Nur für neue Patienten", "fr-FR": "Nouveaux patients uniquement", "da-DK": "Kun nye patienter", "cs-CZ": "Pouze noví pacienti", "ar-EG": "للمرضى الجدد فقط", "zh-CN": "仅限新患者", "zh-TW": "僅限新病患" },
  "Offered": { "de-DE": "Angeboten", "fr-FR": "Proposé", "da-DK": "Tilbydes", "cs-CZ": "Nabízeno", "ar-EG": "متاح", "zh-CN": "提供中", "zh-TW": "提供中" },
  "Answer": { "de-DE": "Antwort", "fr-FR": "Réponse", "da-DK": "Svar", "cs-CZ": "Odpověď", "ar-EG": "الإجابة", "zh-CN": "回答", "zh-TW": "回答" },
  "Shown": { "de-DE": "Angezeigt", "fr-FR": "Affichée", "da-DK": "Vises", "cs-CZ": "Zobrazeno", "ar-EG": "معروض", "zh-CN": "显示", "zh-TW": "顯示" },

  // ── column labels: patients and registrations ──────────────────────────────
  "Date of birth": { "de-DE": "Geburtsdatum", "fr-FR": "Date de naissance", "da-DK": "Fødselsdato", "cs-CZ": "Datum narození", "ar-EG": "تاريخ الميلاد", "zh-CN": "出生日期", "zh-TW": "出生日期" },
  "Mobile": { "de-DE": "Mobilnummer", "fr-FR": "Mobile", "da-DK": "Mobil", "cs-CZ": "Mobil", "ar-EG": "رقم المحمول", "zh-CN": "手机", "zh-TW": "手機" },
  "Email": { "de-DE": "E-Mail", "fr-FR": "E-mail", "da-DK": "E-mail", "cs-CZ": "E-mail", "ar-EG": "البريد الإلكتروني", "zh-CN": "电子邮箱", "zh-TW": "電子郵件" },
  "Someone to ring": { "de-DE": "Notfallkontakt", "fr-FR": "Personne à prévenir", "da-DK": "Kontaktperson", "cs-CZ": "Kontaktní osoba", "ar-EG": "شخص للاتصال به", "zh-CN": "紧急联系人", "zh-TW": "緊急聯絡人" },
  "Allergies": { "de-DE": "Allergien", "fr-FR": "Allergies", "da-DK": "Allergier", "cs-CZ": "Alergie", "ar-EG": "الحساسية", "zh-CN": "过敏史", "zh-TW": "過敏史" },
  "Insurer": { "de-DE": "Versicherung", "fr-FR": "Assureur", "da-DK": "Forsikringsselskab", "cs-CZ": "Pojišťovna", "ar-EG": "شركة التأمين", "zh-CN": "保险公司", "zh-TW": "保險公司" },
  "Policy number": { "de-DE": "Versichertennummer", "fr-FR": "Numéro de contrat", "da-DK": "Policenummer", "cs-CZ": "Číslo pojištěnce", "ar-EG": "رقم وثيقة التأمين", "zh-CN": "保单号", "zh-TW": "保單號碼" },
  "Remind me by email": { "de-DE": "Per E-Mail erinnern", "fr-FR": "Me rappeler par e-mail", "da-DK": "Påmind mig på e-mail", "cs-CZ": "Připomínat e-mailem", "ar-EG": "ذكّرني بالبريد الإلكتروني", "zh-CN": "通过邮件提醒我", "zh-TW": "以電子郵件提醒我" },
  "Status": { "de-DE": "Status", "fr-FR": "Statut", "da-DK": "Status", "cs-CZ": "Stav", "ar-EG": "الحالة", "zh-CN": "状态", "zh-TW": "狀態" },
  "Reference": { "de-DE": "Referenz", "fr-FR": "Référence", "da-DK": "Reference", "cs-CZ": "Reference", "ar-EG": "المرجع", "zh-CN": "编号", "zh-TW": "編號" },
  "Outcome": { "de-DE": "Ergebnis", "fr-FR": "Résultat", "da-DK": "Resultat", "cs-CZ": "Výsledek", "ar-EG": "النتيجة", "zh-CN": "处理结果", "zh-TW": "處理結果" },
  "Handled by": { "de-DE": "Bearbeitet von", "fr-FR": "Traitée par", "da-DK": "Håndteret af", "cs-CZ": "Vyřídil(a)", "ar-EG": "تمت المعالجة بواسطة", "zh-CN": "处理人", "zh-TW": "處理人" },
  "Handled at": { "de-DE": "Bearbeitet am", "fr-FR": "Traitée le", "da-DK": "Håndteret den", "cs-CZ": "Čas vyřízení", "ar-EG": "وقت المعالجة", "zh-CN": "处理时间", "zh-TW": "處理時間" },
  "Created": { "de-DE": "Erstellt", "fr-FR": "Créé le", "da-DK": "Oprettet", "cs-CZ": "Vytvořeno", "ar-EG": "تاريخ الإنشاء", "zh-CN": "创建时间", "zh-TW": "建立時間" },
  "Action key": { "de-DE": "Aktionsschlüssel", "fr-FR": "Clé d’action", "da-DK": "Handlingsnøgle", "cs-CZ": "Klíč akce", "ar-EG": "مفتاح الإجراء", "zh-CN": "操作标识码", "zh-TW": "操作識別碼" },

  // ── column labels: appointments ────────────────────────────────────────────
  "First visit: name": { "de-DE": "Erstbesuch: Name", "fr-FR": "Première visite : nom", "da-DK": "Første besøg: navn", "cs-CZ": "První návštěva: jméno", "ar-EG": "الزيارة الأولى: الاسم", "zh-CN": "初诊：姓名", "zh-TW": "初診：姓名" },
  "First visit: date of birth": { "de-DE": "Erstbesuch: Geburtsdatum", "fr-FR": "Première visite : date de naissance", "da-DK": "Første besøg: fødselsdato", "cs-CZ": "První návštěva: datum narození", "ar-EG": "الزيارة الأولى: تاريخ الميلاد", "zh-CN": "初诊：出生日期", "zh-TW": "初診：出生日期" },
  "First visit: mobile": { "de-DE": "Erstbesuch: Mobilnummer", "fr-FR": "Première visite : mobile", "da-DK": "Første besøg: mobil", "cs-CZ": "První návštěva: mobil", "ar-EG": "الزيارة الأولى: رقم المحمول", "zh-CN": "初诊：手机", "zh-TW": "初診：手機" },
  "First visit: email": { "de-DE": "Erstbesuch: E-Mail", "fr-FR": "Première visite : e-mail", "da-DK": "Første besøg: e-mail", "cs-CZ": "První návštěva: e-mail", "ar-EG": "الزيارة الأولى: البريد الإلكتروني", "zh-CN": "初诊：电子邮箱", "zh-TW": "初診：電子郵件" },
  "Minutes": { "de-DE": "Minuten", "fr-FR": "Minutes", "da-DK": "Minutter", "cs-CZ": "Minuty", "ar-EG": "الدقائق", "zh-CN": "分钟", "zh-TW": "分鐘" },
  "Written off": { "de-DE": "Abgeschrieben", "fr-FR": "Montant remis", "da-DK": "Afskrevet", "cs-CZ": "Odepsáno", "ar-EG": "المبلغ المُعفى", "zh-CN": "已减免", "zh-TW": "已減免" },
  "Paid": { "de-DE": "Bezahlt", "fr-FR": "Payé", "da-DK": "Betalt", "cs-CZ": "Zaplaceno", "ar-EG": "المدفوع", "zh-CN": "已付", "zh-TW": "已付" },
  "Still owing": { "de-DE": "Noch offen", "fr-FR": "Reste à payer", "da-DK": "Udestående", "cs-CZ": "Zbývá zaplatit", "ar-EG": "المبلغ المتبقي", "zh-CN": "尚欠金额", "zh-TW": "尚欠金額" },
  "What it is for": { "de-DE": "Anliegen", "fr-FR": "Motif de la visite", "da-DK": "Hvad det drejer sig om", "cs-CZ": "Důvod návštěvy", "ar-EG": "سبب الزيارة", "zh-CN": "就诊原因", "zh-TW": "看診原因" },
  "Note for the desk": { "de-DE": "Notiz für die Anmeldung", "fr-FR": "Note pour l’accueil", "da-DK": "Note til receptionen", "cs-CZ": "Poznámka pro recepci", "ar-EG": "ملاحظة للاستقبال", "zh-CN": "给前台的备注", "zh-TW": "給櫃台的備註" },
  "Booked by": { "de-DE": "Gebucht von", "fr-FR": "Réservé par", "da-DK": "Booket af", "cs-CZ": "Objednal(a)", "ar-EG": "حجزه", "zh-CN": "预约人", "zh-TW": "預約人" },
  "How it was booked": { "de-DE": "Gebucht über", "fr-FR": "Réservé via", "da-DK": "Booket via", "cs-CZ": "Objednáno přes", "ar-EG": "تم الحجز عبر", "zh-CN": "预约方式", "zh-TW": "預約方式" },
  "Sent to": { "de-DE": "Gesendet an", "fr-FR": "Envoyé à", "da-DK": "Sendt til", "cs-CZ": "Odesláno na", "ar-EG": "أُرسل إلى", "zh-CN": "发送至", "zh-TW": "寄送至" },
  "Visit name": { "de-DE": "Bezeichnung", "fr-FR": "Intitulé", "da-DK": "Betegnelse", "cs-CZ": "Název", "ar-EG": "اسم الزيارة", "zh-CN": "名称", "zh-TW": "名稱" },
  "Checked in at": { "de-DE": "Angemeldet um", "fr-FR": "Heure d’arrivée", "da-DK": "Ankomsttid", "cs-CZ": "Čas příchodu", "ar-EG": "وقت الوصول", "zh-CN": "签到时间", "zh-TW": "報到時間" },
  "Roomed at": { "de-DE": "Aufgerufen um", "fr-FR": "Heure d’entrée en salle", "da-DK": "Kaldt ind", "cs-CZ": "Čas vstupu do ordinace", "ar-EG": "وقت الدخول إلى غرفة الكشف", "zh-CN": "进诊室时间", "zh-TW": "進診間時間" },
  "Seen at": { "de-DE": "Erledigt um", "fr-FR": "Fin de consultation", "da-DK": "Konsultation slut", "cs-CZ": "Čas ošetření", "ar-EG": "وقت انتهاء الكشف", "zh-CN": "就诊完成时间", "zh-TW": "看診完成時間" },
  "Cancelled at": { "de-DE": "Abgesagt am", "fr-FR": "Annulé le", "da-DK": "Aflyst den", "cs-CZ": "Čas zrušení", "ar-EG": "وقت الإلغاء", "zh-CN": "取消时间", "zh-TW": "取消時間" },
  "Late cancellation": { "de-DE": "Kurzfristige Absage", "fr-FR": "Annulation tardive", "da-DK": "Sent afbud", "cs-CZ": "Pozdní zrušení", "ar-EG": "إلغاء متأخر", "zh-CN": "逾时取消", "zh-TW": "逾時取消" },
  "Cancelled by": { "de-DE": "Abgesagt von", "fr-FR": "Annulé par", "da-DK": "Aflyst af", "cs-CZ": "Zrušil(a)", "ar-EG": "ألغاه", "zh-CN": "取消方", "zh-TW": "取消方" },
  "See again in (weeks)": { "de-DE": "Wiedervorstellung in (Wochen)", "fr-FR": "Revoir dans (semaines)", "da-DK": "Ses igen om (uger)", "cs-CZ": "Znovu za (týdnů)", "ar-EG": "المتابعة بعد (أسابيع)", "zh-CN": "复诊间隔（周）", "zh-TW": "回診間隔（週）" },
  "First visit check": { "de-DE": "Prüfung Erstbesuch", "fr-FR": "Vérification première visite", "da-DK": "Tjek af første besøg", "cs-CZ": "Kontrola první návštěvy", "ar-EG": "التحقق من الزيارة الأولى", "zh-CN": "初诊核对", "zh-TW": "初診核對" },

  // ── column labels: payments, write-offs, notes ─────────────────────────────
  "Amount": { "de-DE": "Betrag", "fr-FR": "Montant", "da-DK": "Beløb", "cs-CZ": "Částka", "ar-EG": "المبلغ", "zh-CN": "金额", "zh-TW": "金額" },
  "Method": { "de-DE": "Zahlungsart", "fr-FR": "Moyen de paiement", "da-DK": "Betalingsmåde", "cs-CZ": "Způsob platby", "ar-EG": "طريقة الدفع", "zh-CN": "支付方式", "zh-TW": "付款方式" },
  "Taken by": { "de-DE": "Kassiert von", "fr-FR": "Encaissé par", "da-DK": "Modtaget af", "cs-CZ": "Přijal(a)", "ar-EG": "استلمه", "zh-CN": "收款人", "zh-TW": "收款人" },
  "Paid at": { "de-DE": "Bezahlt am", "fr-FR": "Payé le", "da-DK": "Betalt den", "cs-CZ": "Čas platby", "ar-EG": "وقت الدفع", "zh-CN": "付款时间", "zh-TW": "付款時間" },
  "Voided": { "de-DE": "Storniert", "fr-FR": "Annulé", "da-DK": "Annulleret", "cs-CZ": "Stornováno", "ar-EG": "ملغاة", "zh-CN": "已作废", "zh-TW": "已作廢" },
  "Why it was voided": { "de-DE": "Grund der Stornierung", "fr-FR": "Motif de l’annulation", "da-DK": "Årsag til annullering", "cs-CZ": "Důvod storna", "ar-EG": "سبب الإلغاء", "zh-CN": "作废原因", "zh-TW": "作廢原因" },
  "Voided by": { "de-DE": "Storniert von", "fr-FR": "Annulé par", "da-DK": "Annulleret af", "cs-CZ": "Stornoval(a)", "ar-EG": "ألغاها", "zh-CN": "作废人", "zh-TW": "作廢人" },
  "Reason": { "de-DE": "Grund", "fr-FR": "Motif", "da-DK": "Årsag", "cs-CZ": "Důvod", "ar-EG": "السبب", "zh-CN": "原因", "zh-TW": "原因" },
  "Written off by": { "de-DE": "Abgeschrieben von", "fr-FR": "Remise accordée par", "da-DK": "Afskrevet af", "cs-CZ": "Odepsal(a)", "ar-EG": "سجّل الإعفاء", "zh-CN": "减免人", "zh-TW": "減免人" },
  "Written off at": { "de-DE": "Abgeschrieben am", "fr-FR": "Remise accordée le", "da-DK": "Afskrevet den", "cs-CZ": "Čas odpisu", "ar-EG": "وقت الإعفاء", "zh-CN": "减免时间", "zh-TW": "減免時間" },
  "Written by": { "de-DE": "Verfasst von", "fr-FR": "Rédigée par", "da-DK": "Skrevet af", "cs-CZ": "Napsal(a)", "ar-EG": "كتبها", "zh-CN": "撰写人", "zh-TW": "撰寫人" },

  // ── column labels: recalls, the waiting list, messages ─────────────────────
  "From the visit": { "de-DE": "Vom Termin", "fr-FR": "Suite à la consultation", "da-DK": "Fra besøget", "cs-CZ": "Z návštěvy", "ar-EG": "من الزيارة", "zh-CN": "来源就诊", "zh-TW": "來源看診" },
  "Due on": { "de-DE": "Fällig am", "fr-FR": "À prévoir le", "da-DK": "Forventet dato", "cs-CZ": "Termín kontroly", "ar-EG": "تاريخ المتابعة", "zh-CN": "应复诊日期", "zh-TW": "應回診日期" },
  "What for": { "de-DE": "Anlass", "fr-FR": "Motif", "da-DK": "Formål", "cs-CZ": "Důvod", "ar-EG": "الغرض", "zh-CN": "事由", "zh-TW": "事由" },
  "Why it is not needed": { "de-DE": "Warum nicht nötig", "fr-FR": "Pourquoi ce n’est pas nécessaire", "da-DK": "Hvorfor det ikke er nødvendigt", "cs-CZ": "Proč není potřeba", "ar-EG": "سبب عدم الحاجة", "zh-CN": "无需复诊原因", "zh-TW": "無需回診原因" },
  "Booked visit": { "de-DE": "Gebuchter Termin", "fr-FR": "Rendez-vous réservé", "da-DK": "Booket tid", "cs-CZ": "Objednaný termín", "ar-EG": "الموعد المحجوز", "zh-CN": "已预约的就诊", "zh-TW": "已預約的看診" },
  "Clinician (empty: anyone)": { "de-DE": "Behandler (leer: beliebig)", "fr-FR": "Praticien (vide : n’importe lequel)", "da-DK": "Behandler (tom: hvem som helst)", "cs-CZ": "Zdravotník (prázdné: kdokoli)", "ar-EG": "مقدّم الرعاية (فارغ: أي أحد)", "zh-CN": "医护人员（留空：不限）", "zh-TW": "醫護人員（留空：不限）" },
  "Part of the day": { "de-DE": "Tageszeit", "fr-FR": "Moment de la journée", "da-DK": "Tidspunkt på dagen", "cs-CZ": "Část dne", "ar-EG": "الفترة المفضلة", "zh-CN": "时段", "zh-TW": "時段" },
  "Joined": { "de-DE": "Eingetragen über", "fr-FR": "Inscrit via", "da-DK": "Tilmeldt via", "cs-CZ": "Způsob zápisu", "ar-EG": "طريقة الانضمام", "zh-CN": "加入方式", "zh-TW": "加入方式" },
  "Kind": { "de-DE": "Art", "fr-FR": "Type", "da-DK": "Type", "cs-CZ": "Druh", "ar-EG": "النوع", "zh-CN": "类型", "zh-TW": "類型" },
  "Why": { "de-DE": "Grund", "fr-FR": "Raison", "da-DK": "Årsag", "cs-CZ": "Důvod", "ar-EG": "السبب", "zh-CN": "原因", "zh-TW": "原因" },
  "Due at": { "de-DE": "Fällig am", "fr-FR": "Prévu le", "da-DK": "Sendes den", "cs-CZ": "Odeslat dne", "ar-EG": "موعد الإرسال", "zh-CN": "计划发送时间", "zh-TW": "預定寄送時間" },
  "Sent at": { "de-DE": "Gesendet am", "fr-FR": "Envoyé le", "da-DK": "Sendt den", "cs-CZ": "Čas odeslání", "ar-EG": "وقت الإرسال", "zh-CN": "发送时间", "zh-TW": "寄出時間" },
  "Queued by": { "de-DE": "Veranlasst von", "fr-FR": "Programmé par", "da-DK": "Sat i kø af", "cs-CZ": "Zařadil(a)", "ar-EG": "أُضيفت بواسطة", "zh-CN": "创建人", "zh-TW": "建立人" },

  // ── column labels: the day close ──────────────────────────────────────────
  "Day": { "de-DE": "Tag", "fr-FR": "Jour", "da-DK": "Dag", "cs-CZ": "Den", "ar-EG": "اليوم", "zh-CN": "日期", "zh-TW": "日期" },
  "No-shows marked": { "de-DE": "Als nicht erschienen markiert", "fr-FR": "Absences notées", "da-DK": "Udeblivelser registreret", "cs-CZ": "Označená nedostavení", "ar-EG": "حالات الغياب المسجّلة", "zh-CN": "标记未到诊数", "zh-TW": "標記未到診數" },
  "Cash taken": { "de-DE": "Bar eingenommen", "fr-FR": "Espèces encaissées", "da-DK": "Modtagne kontanter", "cs-CZ": "Přijatá hotovost", "ar-EG": "النقد المُحصَّل", "zh-CN": "现金收入", "zh-TW": "現金收入" },
  "Cash counted": { "de-DE": "Gezähltes Bargeld", "fr-FR": "Espèces comptées", "da-DK": "Optalte kontanter", "cs-CZ": "Spočítaná hotovost", "ar-EG": "النقد المعدود", "zh-CN": "清点现金", "zh-TW": "清點現金" },
  "A note for tomorrow": { "de-DE": "Notiz für morgen", "fr-FR": "Un mot pour demain", "da-DK": "En note til i morgen", "cs-CZ": "Poznámka na zítra", "ar-EG": "ملاحظة للغد", "zh-CN": "留给明天的备注", "zh-TW": "留給明天的備註" },
  "Closed by": { "de-DE": "Abgeschlossen von", "fr-FR": "Clôturée par", "da-DK": "Afsluttet af", "cs-CZ": "Uzavřel(a)", "ar-EG": "أقفله", "zh-CN": "日结人", "zh-TW": "日結人" },
  "Closed at": { "de-DE": "Abgeschlossen am", "fr-FR": "Clôturée le", "da-DK": "Afsluttet den", "cs-CZ": "Čas uzávěrky", "ar-EG": "وقت الإقفال", "zh-CN": "日结时间", "zh-TW": "日結時間" },

  // ── enum values: weekdays ──────────────────────────────────────────────────
  "Monday": { "de-DE": "Montag", "fr-FR": "Lundi", "da-DK": "Mandag", "cs-CZ": "Pondělí", "ar-EG": "الاثنين", "zh-CN": "星期一", "zh-TW": "星期一" },
  "Tuesday": { "de-DE": "Dienstag", "fr-FR": "Mardi", "da-DK": "Tirsdag", "cs-CZ": "Úterý", "ar-EG": "الثلاثاء", "zh-CN": "星期二", "zh-TW": "星期二" },
  "Wednesday": { "de-DE": "Mittwoch", "fr-FR": "Mercredi", "da-DK": "Onsdag", "cs-CZ": "Středa", "ar-EG": "الأربعاء", "zh-CN": "星期三", "zh-TW": "星期三" },
  "Thursday": { "de-DE": "Donnerstag", "fr-FR": "Jeudi", "da-DK": "Torsdag", "cs-CZ": "Čtvrtek", "ar-EG": "الخميس", "zh-CN": "星期四", "zh-TW": "星期四" },
  "Friday": { "de-DE": "Freitag", "fr-FR": "Vendredi", "da-DK": "Fredag", "cs-CZ": "Pátek", "ar-EG": "الجمعة", "zh-CN": "星期五", "zh-TW": "星期五" },
  "Saturday": { "de-DE": "Samstag", "fr-FR": "Samedi", "da-DK": "Lørdag", "cs-CZ": "Sobota", "ar-EG": "السبت", "zh-CN": "星期六", "zh-TW": "星期六" },
  "Sunday": { "de-DE": "Sonntag", "fr-FR": "Dimanche", "da-DK": "Søndag", "cs-CZ": "Neděle", "ar-EG": "الأحد", "zh-CN": "星期日", "zh-TW": "星期日" },

  // ── enum values: a visit's status ──────────────────────────────────────────
  "Booked": { "de-DE": "Gebucht", "fr-FR": "Réservé", "da-DK": "Booket", "cs-CZ": "Objednáno", "ar-EG": "محجوز", "zh-CN": "已预约", "zh-TW": "已預約" },
  "Checked in": { "de-DE": "Angemeldet", "fr-FR": "Arrivé", "da-DK": "Ankommet", "cs-CZ": "Na místě", "ar-EG": "تم تسجيل الوصول", "zh-CN": "已签到", "zh-TW": "已報到" },
  "Roomed": { "de-DE": "Im Behandlungszimmer", "fr-FR": "En salle", "da-DK": "I behandlingsrummet", "cs-CZ": "V ordinaci", "ar-EG": "في غرفة الكشف", "zh-CN": "已进诊室", "zh-TW": "已進診間" },
  "With clinician": { "de-DE": "In Behandlung", "fr-FR": "En consultation", "da-DK": "Hos behandleren", "cs-CZ": "Probíhá ošetření", "ar-EG": "قيد الكشف", "zh-CN": "就诊中", "zh-TW": "看診中" },
  "Ready to go": { "de-DE": "Fertig behandelt", "fr-FR": "Prêt à partir", "da-DK": "Klar til at gå", "cs-CZ": "K odchodu", "ar-EG": "جاهز للمغادرة", "zh-CN": "待离开", "zh-TW": "待離開" },
  "Seen": { "de-DE": "Erledigt", "fr-FR": "Vu", "da-DK": "Afsluttet", "cs-CZ": "Ošetřeno", "ar-EG": "تمّ الكشف", "zh-CN": "已就诊", "zh-TW": "已看診" },
  "No-show": { "de-DE": "Nicht erschienen", "fr-FR": "Absent", "da-DK": "Udeblevet", "cs-CZ": "Nedostavil(a) se", "ar-EG": "لم يحضر", "zh-CN": "未到诊", "zh-TW": "未到診" },
  "Cancelled": { "de-DE": "Abgesagt", "fr-FR": "Annulé", "da-DK": "Aflyst", "cs-CZ": "Zrušeno", "ar-EG": "ملغى", "zh-CN": "已取消", "zh-TW": "已取消" },

  // ── enum values: how a visit was booked, and who cancelled it ──────────────
  "Online": { "de-DE": "Online", "fr-FR": "En ligne", "da-DK": "Online", "cs-CZ": "Online", "ar-EG": "عبر الإنترنت", "zh-CN": "线上", "zh-TW": "線上" },
  "Phone": { "de-DE": "Telefon", "fr-FR": "Téléphone", "da-DK": "Telefon", "cs-CZ": "Telefonicky", "ar-EG": "بالهاتف", "zh-CN": "电话", "zh-TW": "電話" },
  "At the desk": { "de-DE": "An der Anmeldung", "fr-FR": "À l’accueil", "da-DK": "I receptionen", "cs-CZ": "Na recepci", "ar-EG": "في الاستقبال", "zh-CN": "前台", "zh-TW": "櫃台" },
  "Walk-in": { "de-DE": "Ohne Termin", "fr-FR": "Sans rendez-vous", "da-DK": "Uden aftale", "cs-CZ": "Bez objednání", "ar-EG": "بدون موعد", "zh-CN": "现场挂号", "zh-TW": "現場掛號" },
  "The patient": { "de-DE": "Patient", "fr-FR": "Le patient", "da-DK": "Patienten", "cs-CZ": "Pacient", "ar-EG": "المريض", "zh-CN": "患者", "zh-TW": "病患" },
  "The desk": { "de-DE": "Anmeldung", "fr-FR": "L’accueil", "da-DK": "Receptionen", "cs-CZ": "Recepce", "ar-EG": "الاستقبال", "zh-CN": "前台", "zh-TW": "櫃台" },

  // ── enum values: a patient's and a registration's status ───────────────────
  "Active": { "de-DE": "Aktiv", "fr-FR": "Actif", "da-DK": "Aktiv", "cs-CZ": "Aktivní", "ar-EG": "نشط", "zh-CN": "有效", "zh-TW": "有效" },
  "Archived": { "de-DE": "Archiviert", "fr-FR": "Archivé", "da-DK": "Arkiveret", "cs-CZ": "V archivu", "ar-EG": "مؤرشف", "zh-CN": "已归档", "zh-TW": "已封存" },
  "To check": { "de-DE": "Zu prüfen", "fr-FR": "À vérifier", "da-DK": "Skal tjekkes", "cs-CZ": "Ke kontrole", "ar-EG": "بانتظار المراجعة", "zh-CN": "待核对", "zh-TW": "待核對" },
  "Rang": { "de-DE": "Angerufen", "fr-FR": "Appelé", "da-DK": "Ringet op", "cs-CZ": "Zavoláno", "ar-EG": "تم الاتصال", "zh-CN": "已致电", "zh-TW": "已致電" },
  "Accepted": { "de-DE": "Angenommen", "fr-FR": "Accepté", "da-DK": "Godkendt", "cs-CZ": "Přijato", "ar-EG": "مقبول", "zh-CN": "已接受", "zh-TW": "已接受" },
  "Declined": { "de-DE": "Abgelehnt", "fr-FR": "Refusé", "da-DK": "Afvist", "cs-CZ": "Odmítnuto", "ar-EG": "مرفوض", "zh-CN": "已拒绝", "zh-TW": "已拒絕" },
  "Already a patient": { "de-DE": "Bereits bei uns", "fr-FR": "Déjà patient", "da-DK": "Allerede patient", "cs-CZ": "Již je pacientem", "ar-EG": "مسجّل مريضًا بالفعل", "zh-CN": "已是本诊所患者", "zh-TW": "已是本診所病患" },
  "Same person": { "de-DE": "Dieselbe Person", "fr-FR": "Même personne", "da-DK": "Samme person", "cs-CZ": "Stejná osoba", "ar-EG": "الشخص نفسه", "zh-CN": "同一人", "zh-TW": "同一人" },

  // ── enum values: payments ──────────────────────────────────────────────────
  "Card": { "de-DE": "Karte", "fr-FR": "Carte", "da-DK": "Kort", "cs-CZ": "Kartou", "ar-EG": "بطاقة", "zh-CN": "银行卡", "zh-TW": "信用卡" },
  "Cash": { "de-DE": "Bar", "fr-FR": "Espèces", "da-DK": "Kontant", "cs-CZ": "Hotově", "ar-EG": "نقدًا", "zh-CN": "现金", "zh-TW": "現金" },
  "Transfer": { "de-DE": "Überweisung", "fr-FR": "Virement", "da-DK": "Bankoverførsel", "cs-CZ": "Převodem", "ar-EG": "تحويل بنكي", "zh-CN": "转账", "zh-TW": "轉帳" },

  // ── enum values: recalls and the waiting list ──────────────────────────────
  "Due": { "de-DE": "Fällig", "fr-FR": "À relancer", "da-DK": "Skal indkaldes", "cs-CZ": "K pozvání", "ar-EG": "مستحق", "zh-CN": "待复诊", "zh-TW": "待回診" },
  "Note queued": { "de-DE": "Nachricht wartet", "fr-FR": "Message en attente", "da-DK": "Besked i kø", "cs-CZ": "Zpráva ve frontě", "ar-EG": "الرسالة قيد الإرسال", "zh-CN": "通知待发送", "zh-TW": "通知待寄出" },
  "Not needed": { "de-DE": "Nicht nötig", "fr-FR": "Pas nécessaire", "da-DK": "Ikke nødvendig", "cs-CZ": "Není potřeba", "ar-EG": "غير مطلوب", "zh-CN": "无需复诊", "zh-TW": "無需回診" },
  "Any time": { "de-DE": "Jederzeit", "fr-FR": "N’importe quand", "da-DK": "Når som helst", "cs-CZ": "Kdykoli", "ar-EG": "في أي وقت", "zh-CN": "任何时间", "zh-TW": "任何時間" },
  "Mornings": { "de-DE": "Vormittags", "fr-FR": "Le matin", "da-DK": "Formiddag", "cs-CZ": "Dopoledne", "ar-EG": "صباحًا", "zh-CN": "上午", "zh-TW": "上午" },
  "Afternoons": { "de-DE": "Nachmittags", "fr-FR": "L’après-midi", "da-DK": "Eftermiddag", "cs-CZ": "Odpoledne", "ar-EG": "بعد الظهر", "zh-CN": "下午", "zh-TW": "下午" },
  "Waiting": { "de-DE": "Wartet", "fr-FR": "En attente", "da-DK": "Venter", "cs-CZ": "Čeká", "ar-EG": "في الانتظار", "zh-CN": "等待中", "zh-TW": "等候中" },
  "Taken off": { "de-DE": "Entfernt", "fr-FR": "Retiré", "da-DK": "Fjernet", "cs-CZ": "Vyřazeno", "ar-EG": "أُزيل", "zh-CN": "已移除", "zh-TW": "已移除" },

  // ── enum values: a message's kind and status ───────────────────────────────
  "Confirmation": { "de-DE": "Bestätigung", "fr-FR": "Confirmation", "da-DK": "Bekræftelse", "cs-CZ": "Potvrzení", "ar-EG": "تأكيد", "zh-CN": "预约确认", "zh-TW": "預約確認" },
  "Reminder": { "de-DE": "Erinnerung", "fr-FR": "Rappel", "da-DK": "Påmindelse", "cs-CZ": "Připomínka", "ar-EG": "تذكير", "zh-CN": "就诊提醒", "zh-TW": "看診提醒" },
  "Receipt": { "de-DE": "Quittung", "fr-FR": "Reçu", "da-DK": "Kvittering", "cs-CZ": "Stvrzenka", "ar-EG": "إيصال", "zh-CN": "收据", "zh-TW": "收據" },
  "Missed visit": { "de-DE": "Verpasster Termin", "fr-FR": "Rendez-vous manqué", "da-DK": "Udeblivelse", "cs-CZ": "Zmeškaná návštěva", "ar-EG": "زيارة فائتة", "zh-CN": "错过就诊", "zh-TW": "錯過看診" },
  "Waiting to go": { "de-DE": "Wartet auf Versand", "fr-FR": "En attente d’envoi", "da-DK": "Venter på afsendelse", "cs-CZ": "Čeká na odeslání", "ar-EG": "بانتظار الإرسال", "zh-CN": "待发送", "zh-TW": "待寄出" },
  "Sent": { "de-DE": "Gesendet", "fr-FR": "Envoyé", "da-DK": "Sendt", "cs-CZ": "Odesláno", "ar-EG": "أُرسلت", "zh-CN": "已发送", "zh-TW": "已寄出" },
  "Couldn't send": { "de-DE": "Senden fehlgeschlagen", "fr-FR": "Échec de l’envoi", "da-DK": "Kunne ikke sendes", "cs-CZ": "Nepodařilo se odeslat", "ar-EG": "تعذّر الإرسال", "zh-CN": "发送失败", "zh-TW": "寄送失敗" },
  "Not sent": { "de-DE": "Nicht gesendet", "fr-FR": "Non envoyé", "da-DK": "Ikke sendt", "cs-CZ": "Neodesláno", "ar-EG": "لم تُرسل", "zh-CN": "未发送", "zh-TW": "未寄出" },

  // ── the add-ons this app works with, and what each is for ─────────────────
  "Mark public holidays as closures": { "de-DE": "Gesetzliche Feiertage als Schließtage eintragen", "fr-FR": "Marquer les jours fériés comme fermetures", "da-DK": "Markér helligdage som lukkedage", "cs-CZ": "Označit státní svátky jako dny, kdy je zavřeno", "ar-EG": "تحديد العطلات الرسمية كأيام إغلاق", "zh-CN": "把法定节假日标为停诊日", "zh-TW": "把國定假日標為休診日" },
  "Email or print a receipt a patient can claim with": { "de-DE": "Eine Quittung mailen oder drucken, die Patienten bei ihrer Versicherung einreichen können", "fr-FR": "Envoyer par e-mail ou imprimer un reçu que le patient peut présenter à son assurance", "da-DK": "Send eller udskriv en kvittering, som patienten kan få refunderet hos sit forsikringsselskab", "cs-CZ": "Poslat e-mailem nebo vytisknout stvrzenku, kterou pacient uplatní u pojišťovny", "ar-EG": "إرسال إيصال بالبريد الإلكتروني أو طباعته ليقدّمه المريض إلى شركة التأمين", "zh-CN": "通过电子邮件发送或打印收据，供患者向保险公司报销", "zh-TW": "以電子郵件寄送或列印收據，讓病患向保險公司申請理賠" },
  "Receipts for insurers": { "de-DE": "Quittungen für Versicherungen", "fr-FR": "Reçus pour les assurances", "da-DK": "Kvitteringer til forsikringsselskaber", "cs-CZ": "Stvrzenky pro pojišťovny", "ar-EG": "إيصالات لشركات التأمين", "zh-CN": "保险报销收据", "zh-TW": "保險理賠收據" },
  "Receipt for an insurer": { "de-DE": "Quittung für die Versicherung", "fr-FR": "Reçu pour l’assurance", "da-DK": "Kvittering til forsikringen", "cs-CZ": "Stvrzenka pro pojišťovnu", "ar-EG": "إيصال لشركة التأمين", "zh-CN": "供保险报销的收据", "zh-TW": "供保險理賠的收據" },
};
