-- Clinic Desk — the PostgreSQL schema of the stand-alone stack.
--
-- GENERATED by `npm run sample` (db/write-sample.ts) from manifest.json, so a
-- compose install and an Adminium install create the same tables. Do not edit
-- by hand: change the manifest and regenerate. src/data/sample-drift.test.ts
-- fails when this file and the manifest disagree.

DROP TABLE IF EXISTS clinic_day_closes CASCADE;
DROP TABLE IF EXISTS clinic_messages CASCADE;
DROP TABLE IF EXISTS clinic_waiting_list CASCADE;
DROP TABLE IF EXISTS clinic_recalls CASCADE;
DROP TABLE IF EXISTS clinic_check_notes CASCADE;
DROP TABLE IF EXISTS clinic_write_offs CASCADE;
DROP TABLE IF EXISTS clinic_payments CASCADE;
DROP TABLE IF EXISTS clinic_appointments CASCADE;
DROP TABLE IF EXISTS clinic_registrations CASCADE;
DROP TABLE IF EXISTS clinic_patients CASCADE;
DROP TABLE IF EXISTS clinic_faqs CASCADE;
DROP TABLE IF EXISTS clinic_closures CASCADE;
DROP TABLE IF EXISTS clinic_clinician_hours CASCADE;
DROP TABLE IF EXISTS clinic_clinician_visit_types CASCADE;
DROP TABLE IF EXISTS clinic_visit_types CASCADE;
DROP TABLE IF EXISTS clinic_clinicians CASCADE;
DROP TABLE IF EXISTS clinic_opening_hours CASCADE;
DROP TABLE IF EXISTS clinic_settings CASCADE;

CREATE TABLE clinic_settings (
  id SERIAL PRIMARY KEY,
  practice_name VARCHAR(80) NOT NULL,
  mark VARCHAR(2) NOT NULL,
  address VARCHAR(200) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  email VARCHAR(254),
  intro VARCHAR(300),
  directions VARCHAR(500),
  map_link VARCHAR(500),
  entrance_photo VARCHAR(500),
  pay_note VARCHAR(300),
  insurer_note VARCHAR(300),
  privacy_link VARCHAR(500),
  currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  language VARCHAR(16) NOT NULL DEFAULT 'en-US',
  slot_minutes INTEGER NOT NULL DEFAULT 15,
  booking_days INTEGER NOT NULL DEFAULT 10,
  min_notice_minutes INTEGER NOT NULL DEFAULT 60,
  new_patients_online BOOLEAN NOT NULL DEFAULT TRUE,
  online_booking_on BOOLEAN NOT NULL DEFAULT TRUE,
  no_show_minutes INTEGER NOT NULL DEFAULT 15,
  cancel_hours INTEGER NOT NULL DEFAULT 24,
  reminders_on BOOLEAN NOT NULL DEFAULT TRUE,
  default_lead_hours INTEGER NOT NULL DEFAULT 24,
  kiosk_on BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE clinic_opening_hours (
  id SERIAL PRIMARY KEY,
  weekday TEXT NOT NULL CHECK (weekday IN ('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun')) UNIQUE,
  open BOOLEAN NOT NULL DEFAULT TRUE,
  opens VARCHAR(5) NOT NULL DEFAULT '08:30',
  closes VARCHAR(5) NOT NULL DEFAULT '17:30',
  break_start VARCHAR(5),
  break_end VARCHAR(5)
);

CREATE TABLE clinic_clinicians (
  id SERIAL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  short_name VARCHAR(40) NOT NULL,
  role_label VARCHAR(60) NOT NULL,
  color VARCHAR(7) NOT NULL DEFAULT '#0369a1',
  photo VARCHAR(500),
  bio VARCHAR(400),
  bookable_online BOOLEAN NOT NULL DEFAULT TRUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  position INTEGER NOT NULL DEFAULT 0,
  staff_email VARCHAR(254)
);

CREATE TABLE clinic_visit_types (
  id SERIAL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  short_name VARCHAR(30) NOT NULL,
  minutes INTEGER NOT NULL DEFAULT 15,
  fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
  color VARCHAR(7) NOT NULL DEFAULT '#3b6fbd',
  icon VARCHAR(40) NOT NULL DEFAULT 'stethoscope',
  bookable_online BOOLEAN NOT NULL DEFAULT TRUE,
  new_patients_only BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE clinic_clinician_visit_types (
  id SERIAL PRIMARY KEY,
  clinician_id INTEGER NOT NULL REFERENCES clinic_clinicians (id),
  visit_type_id INTEGER NOT NULL REFERENCES clinic_visit_types (id)
);

CREATE TABLE clinic_clinician_hours (
  id SERIAL PRIMARY KEY,
  clinician_id INTEGER NOT NULL REFERENCES clinic_clinicians (id),
  weekday TEXT NOT NULL CHECK (weekday IN ('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun')),
  opens VARCHAR(5) NOT NULL DEFAULT '08:30',
  closes VARCHAR(5) NOT NULL DEFAULT '17:30',
  break_start VARCHAR(5),
  break_end VARCHAR(5)
);

CREATE TABLE clinic_closures (
  id SERIAL PRIMARY KEY,
  client_key VARCHAR(36) UNIQUE,
  clinician_id INTEGER REFERENCES clinic_clinicians (id),
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  label VARCHAR(80) NOT NULL,
  note VARCHAR(280),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_faqs (
  id SERIAL PRIMARY KEY,
  question VARCHAR(200) NOT NULL,
  answer VARCHAR(1000) NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clinic_patients (
  id SERIAL PRIMARY KEY,
  client_key VARCHAR(36) UNIQUE,
  name VARCHAR(120) NOT NULL,
  born_on DATE NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  email VARCHAR(254),
  address VARCHAR(300),
  emergency_contact VARCHAR(200),
  allergies_note VARCHAR(200),
  insurer VARCHAR(80),
  policy_ref VARCHAR(60),
  language VARCHAR(16),
  remind_email BOOLEAN NOT NULL DEFAULT TRUE,
  remind_lead_hours INTEGER NOT NULL DEFAULT 24,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_registrations (
  id SERIAL PRIMARY KEY,
  ref VARCHAR(12) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  born_on DATE NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  email VARCHAR(254),
  address VARCHAR(300),
  emergency_contact VARCHAR(200),
  language VARCHAR(16),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'rang', 'accepted', 'declined', 'duplicate')),
  patient_id INTEGER REFERENCES clinic_patients (id),
  outcome VARCHAR(200),
  note VARCHAR(280),
  handled_by VARCHAR(120),
  handled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_appointments (
  id SERIAL PRIMARY KEY,
  ref VARCHAR(12) NOT NULL UNIQUE,
  patient_id INTEGER REFERENCES clinic_patients (id),
  new_name VARCHAR(120),
  new_born_on DATE,
  new_mobile VARCHAR(32),
  new_email VARCHAR(254),
  clinician_id INTEGER REFERENCES clinic_clinicians (id),
  visit_type_id INTEGER NOT NULL REFERENCES clinic_visit_types (id),
  starts_at TIMESTAMPTZ NOT NULL,
  minutes INTEGER NOT NULL DEFAULT 15,
  fee NUMERIC(12, 2),
  waived NUMERIC(12, 2),
  paid NUMERIC(12, 2),
  balance NUMERIC(12, 2),
  reason VARCHAR(240),
  desk_note VARCHAR(280),
  status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'checked_in', 'roomed', 'with_clinician', 'ready', 'seen', 'no_show', 'cancelled')),
  channel TEXT NOT NULL DEFAULT 'desk' CHECK (channel IN ('online', 'phone', 'desk', 'walk_in', 'waiting_list', 'recall')),
  checked_in_at TIMESTAMPTZ,
  roomed_at TIMESTAMPTZ,
  seen_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  late_cancel BOOLEAN NOT NULL DEFAULT FALSE,
  cancelled_by TEXT CHECK (cancelled_by IN ('patient', 'desk')),
  recall_weeks INTEGER,
  language VARCHAR(16),
  booked_by VARCHAR(120),
  check_status TEXT CHECK (check_status IN ('to_check', 'rang', 'accepted', 'linked', 'declined')),
  client_key VARCHAR(36) UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_payments (
  id SERIAL PRIMARY KEY,
  appointment_id INTEGER NOT NULL REFERENCES clinic_appointments (id),
  patient_id INTEGER REFERENCES clinic_patients (id),
  visit_type_id INTEGER REFERENCES clinic_visit_types (id),
  clinician_id INTEGER REFERENCES clinic_clinicians (id),
  amount NUMERIC(12, 2) NOT NULL,
  method TEXT NOT NULL DEFAULT 'card' CHECK (method IN ('card', 'cash', 'transfer')),
  taken_by VARCHAR(120),
  paid_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  voided BOOLEAN NOT NULL DEFAULT FALSE,
  void_reason VARCHAR(200),
  voided_by VARCHAR(120),
  client_key VARCHAR(36) UNIQUE
);

CREATE TABLE clinic_write_offs (
  id SERIAL PRIMARY KEY,
  appointment_id INTEGER NOT NULL REFERENCES clinic_appointments (id),
  amount NUMERIC(12, 2) NOT NULL,
  reason VARCHAR(200) NOT NULL,
  written_by VARCHAR(120),
  written_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  client_key VARCHAR(36) UNIQUE
);

CREATE TABLE clinic_check_notes (
  id SERIAL PRIMARY KEY,
  registration_id INTEGER REFERENCES clinic_registrations (id),
  appointment_id INTEGER REFERENCES clinic_appointments (id),
  note VARCHAR(280) NOT NULL,
  written_by VARCHAR(120),
  client_key VARCHAR(36) UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_recalls (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES clinic_patients (id),
  from_appointment_id INTEGER REFERENCES clinic_appointments (id),
  visit_type_id INTEGER REFERENCES clinic_visit_types (id),
  clinician_id INTEGER NOT NULL REFERENCES clinic_clinicians (id),
  client_key VARCHAR(36) UNIQUE,
  weeks INTEGER NOT NULL,
  due_on DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'due' CHECK (status IN ('due', 'noted', 'booked', 'not_needed')),
  reason VARCHAR(120),
  dismiss_reason VARCHAR(120),
  booked_appointment_id INTEGER REFERENCES clinic_appointments (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_waiting_list (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES clinic_patients (id),
  visit_type_id INTEGER NOT NULL REFERENCES clinic_visit_types (id),
  clinician_id INTEGER REFERENCES clinic_clinicians (id),
  part_of_day TEXT NOT NULL DEFAULT 'any' CHECK (part_of_day IN ('any', 'mornings', 'afternoons')),
  status TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting', 'booked', 'removed')),
  channel TEXT NOT NULL DEFAULT 'desk' CHECK (channel IN ('online', 'desk')),
  booked_appointment_id INTEGER REFERENCES clinic_appointments (id),
  note VARCHAR(280),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_messages (
  id SERIAL PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('confirmation', 'reminder', 'missed', 'recall', 'cancelled', 'receipt')),
  patient_id INTEGER REFERENCES clinic_patients (id),
  appointment_id INTEGER REFERENCES clinic_appointments (id),
  recall_id INTEGER REFERENCES clinic_recalls (id),
  closure_id INTEGER REFERENCES clinic_closures (id),
  payment_id INTEGER REFERENCES clinic_payments (id),
  to_address VARCHAR(254),
  language VARCHAR(16),
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'sent', 'failed', 'skipped')),
  error VARCHAR(300),
  due_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  created_by VARCHAR(120),
  client_key VARCHAR(36) UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clinic_day_closes (
  id SERIAL PRIMARY KEY,
  day DATE NOT NULL UNIQUE,
  no_shows_marked INTEGER NOT NULL DEFAULT 0,
  cash_expected NUMERIC(12, 2) NOT NULL DEFAULT 0,
  cash_counted NUMERIC(12, 2),
  note VARCHAR(500),
  closed_by VARCHAR(120),
  closed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_clinician_visit_types_clinician_id ON clinic_clinician_visit_types (clinician_id);
CREATE INDEX idx_clinician_visit_types_visit_type_id ON clinic_clinician_visit_types (visit_type_id);
CREATE INDEX idx_clinician_hours_clinician_id ON clinic_clinician_hours (clinician_id);
CREATE INDEX idx_closures_clinician_id ON clinic_closures (clinician_id);
CREATE INDEX idx_registrations_patient_id ON clinic_registrations (patient_id);
CREATE INDEX idx_appointments_patient_id ON clinic_appointments (patient_id);
CREATE INDEX idx_appointments_clinician_id ON clinic_appointments (clinician_id);
CREATE INDEX idx_appointments_visit_type_id ON clinic_appointments (visit_type_id);
CREATE INDEX idx_payments_appointment_id ON clinic_payments (appointment_id);
CREATE INDEX idx_payments_patient_id ON clinic_payments (patient_id);
CREATE INDEX idx_payments_visit_type_id ON clinic_payments (visit_type_id);
CREATE INDEX idx_payments_clinician_id ON clinic_payments (clinician_id);
CREATE INDEX idx_write_offs_appointment_id ON clinic_write_offs (appointment_id);
CREATE INDEX idx_check_notes_registration_id ON clinic_check_notes (registration_id);
CREATE INDEX idx_check_notes_appointment_id ON clinic_check_notes (appointment_id);
CREATE INDEX idx_recalls_patient_id ON clinic_recalls (patient_id);
CREATE INDEX idx_recalls_from_appointment_id ON clinic_recalls (from_appointment_id);
CREATE INDEX idx_recalls_visit_type_id ON clinic_recalls (visit_type_id);
CREATE INDEX idx_recalls_clinician_id ON clinic_recalls (clinician_id);
CREATE INDEX idx_recalls_booked_appointment_id ON clinic_recalls (booked_appointment_id);
CREATE INDEX idx_waiting_list_patient_id ON clinic_waiting_list (patient_id);
CREATE INDEX idx_waiting_list_visit_type_id ON clinic_waiting_list (visit_type_id);
CREATE INDEX idx_waiting_list_clinician_id ON clinic_waiting_list (clinician_id);
CREATE INDEX idx_waiting_list_booked_appointment_id ON clinic_waiting_list (booked_appointment_id);
CREATE INDEX idx_messages_patient_id ON clinic_messages (patient_id);
CREATE INDEX idx_messages_appointment_id ON clinic_messages (appointment_id);
CREATE INDEX idx_messages_recall_id ON clinic_messages (recall_id);
CREATE INDEX idx_messages_closure_id ON clinic_messages (closure_id);
CREATE INDEX idx_messages_payment_id ON clinic_messages (payment_id);
