-- Clinic Desk — the stand-alone stack's sample practice.
--
-- GENERATED by `npm run sample` (db/write-sample.ts) from the same bundle an
-- operator adds from Adminium (seeds/clinic.sample.json), resolved at the
-- moment the design is drawn: Tuesday 28 July 2026, 09:20 in London. Loaded
-- at any time, the database is that morning; the words are the English ones.
-- Do not edit by hand.

BEGIN;

INSERT INTO clinic_settings (id, practice_name, mark, address, phone, email, intro, directions, map_link, entrance_photo, pay_note, insurer_note, privacy_link, currency, language, slot_minutes, booking_days, min_notice_minutes, new_patients_online, online_booking_on, no_show_minutes, cancel_hours, reminders_on, default_lead_hours, kiosk_on) VALUES
  (1, 'Rowan Health', 'RH', '12 Rowan Walk, Ashgrove BS7 4QN', '0117 496 0142', 'rowan.desk@example.com', 'A small practice on Rowan Walk with a level entrance.', 'Two minutes from the Ashgrove bus stop. Bicycle stands by the side gate; no car park, but the street is unrestricted after 10.', NULL, NULL, 'Card, cash or a transfer on the day. We can take part of it now and the rest later.', 'Bring your policy number and we will send the paperwork on for you.', NULL, 'GBP', 'en-US', 15, 10, 60, TRUE, TRUE, 15, 24, TRUE, 24, TRUE);

INSERT INTO clinic_opening_hours (id, weekday, open, opens, closes, break_start, break_end) VALUES
  (1, 'mon', TRUE, '08:30', '17:30', '12:30', '13:15'),
  (2, 'tue', TRUE, '08:30', '17:30', '12:30', '13:15'),
  (3, 'wed', TRUE, '08:30', '17:30', '12:30', '13:15'),
  (4, 'thu', TRUE, '08:30', '17:30', '12:30', '13:15'),
  (5, 'fri', TRUE, '08:30', '17:30', '12:30', '13:15'),
  (6, 'sat', FALSE, '08:30', '17:30', NULL, NULL),
  (7, 'sun', FALSE, '08:30', '17:30', NULL, NULL);

INSERT INTO clinic_clinicians (id, name, short_name, role_label, color, photo, bio, bookable_online, active, position, staff_email) VALUES
  (1, 'Dr Amara Osei', 'Dr Osei', 'GP', '#2f6ad9', NULL, 'Routine checks, follow-ups and new registrations. Tuesday and Thursday mornings fill first.', TRUE, TRUE, 0, 'amara.osei@example.com'),
  (2, 'Dr Piotr Nowak', 'Dr Nowak', 'GP', '#7c5cd0', NULL, 'Routine checks and new registrations. Happy to see the whole household in one run.', TRUE, TRUE, 1, 'piotr.nowak@example.com'),
  (3, 'Nadia Haddad', 'Nadia', 'Physiotherapist', '#0f8a6a', NULL, 'Forty-five minutes for rehab and follow-ups. Bring shorts or loose trousers.', TRUE, TRUE, 2, 'nadia.haddad@example.com'),
  (4, 'Tom Villaseñor', 'Tom', 'Practice nurse', '#b25e09', NULL, 'Dressings, jabs and stitches out. Short visits, quick in and out.', TRUE, TRUE, 3, 'tom.villasenor@example.com');

INSERT INTO clinic_visit_types (id, name, short_name, minutes, fee, color, icon, bookable_online, new_patients_only, active, position) VALUES
  (1, 'Routine check', 'Routine', 15, 45, '#3b6fbd', 'stethoscope', TRUE, FALSE, TRUE, 0),
  (2, 'New patient', 'New patient', 30, 70, '#6d5bd0', 'user-plus', TRUE, TRUE, TRUE, 1),
  (3, 'Physiotherapy', 'Physio', 45, 60, '#0f8a6a', 'person-standing', TRUE, FALSE, TRUE, 2),
  (4, 'Nurse — dressing or vaccination', 'Nurse', 15, 28, '#b25e09', 'syringe', TRUE, FALSE, TRUE, 3);

INSERT INTO clinic_clinician_visit_types (id, clinician_id, visit_type_id) VALUES
  (1, 1, 1),
  (2, 1, 2),
  (3, 2, 1),
  (4, 2, 2),
  (5, 3, 3),
  (6, 4, 4);

INSERT INTO clinic_clinician_hours (id, clinician_id, weekday, opens, closes, break_start, break_end) VALUES
  (1, 4, 'mon', '08:30', '15:00', '12:30', '13:15'),
  (2, 4, 'tue', '08:30', '15:00', '12:30', '13:15'),
  (3, 4, 'wed', '08:30', '15:00', '12:30', '13:15'),
  (4, 4, 'thu', '08:30', '15:00', '12:30', '13:15'),
  (5, 4, 'fri', '08:30', '12:30', NULL, NULL);

INSERT INTO clinic_closures (id, client_key, clinician_id, from_date, to_date, label, note, active, created_at) VALUES
  (1, NULL, 3, '2026-08-07', '2026-08-07', 'Nadia away', 'Teaching for the day — no physiotherapy times.', TRUE, '2026-07-27T12:20:00.000Z'::timestamptz),
  (2, NULL, 1, '2026-08-10', '2026-08-14', 'Dr Osei away', 'Annual leave. Dr Nowak covers the routine checks.', TRUE, '2026-07-16T08:20:00.000Z'::timestamptz),
  (3, NULL, NULL, '2026-08-31', '2026-08-31', 'Staff training day', 'The whole practice is shut for staff training.', TRUE, '2026-07-07T08:20:00.000Z'::timestamptz);

INSERT INTO clinic_faqs (id, question, answer, position, active) VALUES
  (1, 'What if I am running late?', 'Come anyway and speak to the desk. If you are more than {no_show_minutes} minutes past your start we may have to move you to the next open time, but we will always try to fit you in.', 0, TRUE),
  (2, 'How do I change or cancel?', 'From My visits, or ring the desk on {phone}. There is no charge until {cancel_hours} hours before the start. Inside that we still will not charge you, but the time is hard to give to somebody else — so tell us as soon as you know.', 1, TRUE),
  (3, 'What should I bring?', 'Your mobile, so you have the reference, and anything the desk asked for when you booked. If you told us something in the note, it is already on the day sheet.', 2, TRUE),
  (4, 'Can I book for somebody else?', 'Yes. Book it in their name and add a line for the desk so we know who is coming with them.', 3, TRUE),
  (5, 'How long will I wait once I am there?', 'The board at the desk shows how long each person has been in the building. Most people are seen within ten minutes of their start; if it slips past twenty, ask us and we will find out where things are.', 4, TRUE),
  (6, 'Do you see children?', 'Yes, from birth upwards. Bring an adult who can stay for the whole visit.', 5, TRUE);

INSERT INTO clinic_patients (id, client_key, name, born_on, mobile, email, address, emergency_contact, allergies_note, insurer, policy_ref, language, remind_email, remind_lead_hours, status, created_at) VALUES
  (1, NULL, 'Harriet Blythe', '1948-03-11', '07700 900118', NULL, '8 Linden Row, Ashgrove BS7 4RF', 'Ruth Blythe · 07700 900119', NULL, NULL, NULL, 'en-US', FALSE, 24, 'active', '2022-07-29T08:20:00.000Z'::timestamptz),
  (2, NULL, 'Ewan Pryce', '1991-06-02', '07700 900142', 'ewan@example.com', NULL, NULL, 'Latex', NULL, NULL, 'en-US', TRUE, 24, 'active', '2025-06-03T08:20:00.000Z'::timestamptz),
  (3, NULL, 'Delphine Auclair', '1979-11-23', '07700 900133', 'delphine@example.com', NULL, NULL, NULL, NULL, NULL, 'fr-FR', TRUE, 48, 'active', '2024-11-25T08:20:00.000Z'::timestamptz),
  (4, NULL, 'Inés Varela', '1996-01-30', '07700 900107', 'ines@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', TRUE, 24, 'active', '2026-07-24T08:20:00.000Z'::timestamptz),
  (5, NULL, 'Solveig Rasmussen', '1962-09-14', '07700 900155', 'solveig@example.com', '21 Orchard Way, Ashgrove BS7 4UB', NULL, NULL, NULL, NULL, 'da-DK', TRUE, 24, 'active', '2024-07-28T08:20:00.000Z'::timestamptz),
  (6, NULL, 'Kofi Mensah', '1988-04-05', '07700 900121', 'kofi@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', TRUE, 12, 'active', '2026-07-22T08:20:00.000Z'::timestamptz),
  (7, NULL, 'Nour Khalil', '2004-12-19', '07700 900190', 'nour@example.com', NULL, NULL, NULL, NULL, NULL, 'ar-EG', TRUE, 24, 'active', '2025-09-01T08:20:00.000Z'::timestamptz),
  (8, NULL, 'Beatriz Salgado', '1955-07-08', '07700 900176', 'beatriz@example.com', '5 Quarry Lane, Ashgrove BS7 4TT', NULL, NULL, NULL, NULL, 'en-US', TRUE, 48, 'active', '2024-02-29T08:20:00.000Z'::timestamptz),
  (9, NULL, 'Malachy Doyle', '1972-02-27', '07700 900168', 'malachy@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', FALSE, 24, 'active', '2025-02-03T08:20:00.000Z'::timestamptz),
  (10, NULL, 'Zofia Lange', '1999-08-16', '07700 900112', 'zofia@example.com', NULL, NULL, NULL, NULL, NULL, 'cs-CZ', TRUE, 24, 'active', '2026-07-25T08:20:00.000Z'::timestamptz),
  (11, NULL, 'Priya Raman', '1983-05-21', '07700 900149', 'priya@example.com', NULL, NULL, NULL, 'Harbour Mutual', 'HM-40371102', 'en-US', TRUE, 48, 'active', '2025-07-03T08:20:00.000Z'::timestamptz),
  (12, NULL, 'Cormac Ellery', '1968-10-02', '07700 900164', 'cormac@example.com', NULL, NULL, NULL, 'Harbour Mutual', 'HM-40218871', 'en-US', TRUE, 24, 'active', '2025-11-10T08:20:00.000Z'::timestamptz),
  (13, NULL, 'Saoirse Whelan', '2018-05-30', '07700 900103', 'saoirse@example.com', NULL, 'Siobhan Whelan · 07700 900104', 'Peanuts', NULL, NULL, 'en-US', TRUE, 24, 'active', '2022-06-19T08:20:00.000Z'::timestamptz),
  (14, NULL, 'Tobias Lindqvist', '1942-01-17', '07700 900187', NULL, '2 Mill Yard, Ashgrove BS7 4NA', 'Ingrid Lindqvist · 07700 900188', 'Adhesive dressings', NULL, NULL, 'en-US', FALSE, 24, 'active', '2020-10-27T08:20:00.000Z'::timestamptz),
  (15, NULL, 'Amaia Etxeberria', '1990-03-08', '07700 900129', 'amaia@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', TRUE, 12, 'active', '2025-05-04T08:20:00.000Z'::timestamptz),
  (16, NULL, 'Rufus Adeyemi', '2020-02-11', '07700 900158', 'rufus@example.com', NULL, 'Grace Adeyemi · 07700 900159', NULL, NULL, NULL, 'en-US', TRUE, 24, 'active', '2022-03-11T08:20:00.000Z'::timestamptz),
  (17, NULL, 'Remi Adeyemi', '2020-02-11', '07700 900158', 'remi@example.com', NULL, 'Grace Adeyemi · 07700 900159', NULL, NULL, NULL, 'en-US', TRUE, 24, 'active', '2022-03-11T08:20:00.000Z'::timestamptz),
  (18, NULL, 'Martha Okonjo', '1951-12-04', '07700 900194', 'martha@example.com', '14 Rowan Walk, Ashgrove BS7 4QN', NULL, NULL, NULL, NULL, 'en-US', TRUE, 48, 'active', '2021-05-15T08:20:00.000Z'::timestamptz),
  (19, NULL, 'Dev Chatterjee', '1977-07-19', '07700 900137', 'dev@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', TRUE, 12, 'active', '2025-10-01T08:20:00.000Z'::timestamptz),
  (20, NULL, 'Leila Farsi', '2001-09-27', '07700 900171', 'leila@example.com', NULL, NULL, 'Shellfish', NULL, NULL, 'en-US', TRUE, 24, 'active', '2026-01-09T08:20:00.000Z'::timestamptz),
  (21, NULL, 'Gustav Holm', '1959-04-23', '07700 900182', 'gustav@example.com', NULL, NULL, NULL, 'Northgate Health', 'NG-7721-0934', 'da-DK', TRUE, 48, 'active', '2024-08-27T08:20:00.000Z'::timestamptz),
  (22, NULL, 'Wren Calloway', '1994-11-06', '07700 900115', 'wren@example.com', '19 Elm Parade, Ashgrove BS7 4PL', NULL, NULL, NULL, NULL, 'en-US', TRUE, 24, 'active', '2025-04-04T08:20:00.000Z'::timestamptz),
  (23, NULL, 'Hamid Sarraf', '1966-06-15', '07700 900161', 'hamid@example.com', NULL, NULL, NULL, NULL, NULL, 'ar-EG', TRUE, 24, 'active', '2025-11-20T08:20:00.000Z'::timestamptz),
  (24, NULL, 'Juno Ferreira', '2011-08-09', '07700 900109', 'juno@example.com', NULL, 'Marta Ferreira · 07700 900110', 'Bee stings', NULL, NULL, 'en-US', TRUE, 24, 'active', '2023-04-15T08:20:00.000Z'::timestamptz),
  (25, NULL, 'Eleni Vasilakis', '1945-10-21', '07700 900198', NULL, '6 Church Steps, Ashgrove BS7 4QA', NULL, NULL, NULL, NULL, 'en-US', FALSE, 24, 'active', '2021-02-04T08:20:00.000Z'::timestamptz),
  (26, NULL, 'Bram de Vries', '1985-02-14', '07700 900144', 'bram@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', TRUE, 24, 'active', '2026-02-28T08:20:00.000Z'::timestamptz),
  (27, NULL, 'Odette Baptiste', '1973-01-09', '07700 900153', 'odette@example.com', NULL, NULL, NULL, NULL, NULL, 'fr-FR', TRUE, 24, 'active', '2026-07-16T08:20:00.000Z'::timestamptz),
  (28, NULL, 'Yusuf Demir', '2009-03-25', '07700 900126', 'yusuf@example.com', NULL, 'Elif Demir · 07700 900127', NULL, NULL, NULL, 'de-DE', TRUE, 24, 'active', '2024-02-09T08:20:00.000Z'::timestamptz),
  (29, NULL, 'Clara Nwosu', '1998-06-11', '07700 900131', 'clara@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', TRUE, 24, 'active', '2025-08-12T08:20:00.000Z'::timestamptz),
  (30, NULL, 'Héctor Salazar', '1969-09-03', '07700 900147', 'hector@example.com', NULL, NULL, NULL, NULL, NULL, 'en-US', FALSE, 24, 'active', '2025-12-20T08:20:00.000Z'::timestamptz),
  (31, NULL, 'Maeve Corrigan', '2015-04-18', '07700 900105', 'maeve@example.com', NULL, 'Niamh Corrigan · 07700 900106', 'Peanuts', NULL, NULL, 'en-US', TRUE, 24, 'active', '2023-01-05T08:20:00.000Z'::timestamptz);

INSERT INTO clinic_registrations (id, ref, name, born_on, mobile, email, address, emergency_contact, language, status, patient_id, outcome, note, handled_by, handled_at, created_at) VALUES
  (1, 'RG-S4EQ', 'Ruth Okafor', '1958-05-30', '07700 900214', 'ruth.okafor@example.com', '3 Mill Yard, Ashgrove BS7 4NA', 'Daniel Okafor · 07700 900215', 'en-US', 'rang', NULL, NULL, NULL, 'Ivy Ferreira', '2026-07-27T15:05:00.000Z'::timestamptz, '2026-07-24T06:20:00.000Z'::timestamptz),
  (2, 'RG-S9EJ', 'Anouk Brenner', '1990-04-21', '07700 900216', 'anouk.b@example.com', '4 Linden Row, Ashgrove BS7 4RF', 'Pieter Brenner · 07700 900211', 'de-DE', 'new', NULL, NULL, NULL, NULL, NULL, '2026-07-26T05:20:00.000Z'::timestamptz),
  (3, 'RG-SWDS', 'Tariq Mahmood', '1985-08-30', '07700 900199', 'tariq.m@example.com', '7 Quarry Lane, Ashgrove BS7 4TT', 'Sana Mahmood · 07700 900212', 'en-US', 'new', NULL, NULL, NULL, NULL, NULL, '2026-07-28T07:10:00.000Z'::timestamptz);

INSERT INTO clinic_appointments (id, ref, patient_id, new_name, new_born_on, new_mobile, new_email, clinician_id, visit_type_id, starts_at, minutes, fee, waived, paid, balance, reason, desk_note, status, channel, checked_in_at, roomed_at, seen_at, cancelled_at, late_cancel, cancelled_by, recall_weeks, language, booked_by, check_status, client_key, created_at) VALUES
  (1, 'RH-SF0A', 14, NULL, NULL, NULL, NULL, 1, 1, '2026-01-13T10:00:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Annual check', NULL, 'seen', 'phone', '2026-01-13T09:54:00.000Z'::timestamptz, '2026-01-13T10:02:00.000Z'::timestamptz, '2026-01-13T10:15:00.000Z'::timestamptz, NULL, FALSE, NULL, 24, NULL, 'Callum Reid', NULL, NULL, '2026-01-06T10:10:00.000Z'::timestamptz),
  (2, 'RH-S47Y', 29, NULL, NULL, NULL, NULL, 2, 1, '2026-01-27T10:30:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Review appointment', NULL, 'seen', 'online', '2026-01-27T10:24:00.000Z'::timestamptz, '2026-01-27T10:32:00.000Z'::timestamptz, '2026-01-27T10:45:00.000Z'::timestamptz, NULL, FALSE, NULL, 28, NULL, NULL, NULL, NULL, '2026-01-21T10:15:00.000Z'::timestamptz),
  (3, 'RH-S3WP', 23, NULL, NULL, NULL, NULL, 1, 1, '2026-02-03T09:15:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Annual check', NULL, 'seen', 'phone', '2026-02-03T09:09:00.000Z'::timestamptz, '2026-02-03T09:17:00.000Z'::timestamptz, '2026-02-03T09:30:00.000Z'::timestamptz, NULL, FALSE, NULL, 25, NULL, 'Callum Reid', NULL, NULL, '2026-01-22T14:10:00.000Z'::timestamptz),
  (4, 'RH-SF8M', 25, NULL, NULL, NULL, NULL, 2, 1, '2026-02-24T14:00:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Follow-up visit', NULL, 'seen', 'phone', '2026-02-24T13:54:00.000Z'::timestamptz, '2026-02-24T14:02:00.000Z'::timestamptz, '2026-02-24T14:15:00.000Z'::timestamptz, NULL, FALSE, NULL, 20, NULL, 'Callum Reid', NULL, NULL, '2026-02-16T09:55:00.000Z'::timestamptz),
  (5, 'RH-SB22', 24, NULL, NULL, NULL, NULL, 4, 4, '2026-04-14T08:30:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Travel jabs', NULL, 'cancelled', 'phone', NULL, NULL, NULL, '2026-04-14T07:05:00.000Z'::timestamptz, TRUE, 'patient', NULL, NULL, 'Callum Reid', NULL, NULL, '2026-04-07T14:10:00.000Z'::timestamptz),
  (6, 'RH-SQZP', 1, NULL, NULL, NULL, NULL, 1, 1, '2026-04-28T08:30:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Annual check', NULL, 'seen', 'phone', '2026-04-28T08:24:00.000Z'::timestamptz, '2026-04-28T08:32:00.000Z'::timestamptz, '2026-04-28T08:45:00.000Z'::timestamptz, NULL, FALSE, NULL, 52, NULL, 'Callum Reid', NULL, NULL, '2026-04-27T15:25:00.000Z'::timestamptz),
  (7, 'RH-S4FX', 18, NULL, NULL, NULL, NULL, 4, 4, '2026-05-05T10:00:00.000Z'::timestamptz, 15, 28, 0, 28, 0, 'Dressing change', NULL, 'seen', 'desk', '2026-05-05T09:54:00.000Z'::timestamptz, '2026-05-05T10:02:00.000Z'::timestamptz, '2026-05-05T10:15:00.000Z'::timestamptz, NULL, FALSE, NULL, 12, NULL, 'Callum Reid', NULL, NULL, '2026-05-01T13:55:00.000Z'::timestamptz),
  (8, 'RH-SJ2D', 9, NULL, NULL, NULL, NULL, 2, 1, '2026-05-19T09:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'no_show', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Callum Reid', NULL, NULL, '2026-05-08T09:10:00.000Z'::timestamptz),
  (9, 'RH-SAVA', 11, NULL, NULL, NULL, NULL, 1, 1, '2026-06-02T10:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Review appointment', NULL, 'cancelled', 'online', NULL, NULL, NULL, '2026-05-27T14:20:00.000Z'::timestamptz, FALSE, 'desk', NULL, NULL, NULL, NULL, NULL, '2026-05-22T07:30:00.000Z'::timestamptz),
  (10, 'RH-SJYK', 19, NULL, NULL, NULL, NULL, 3, 3, '2026-06-10T13:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder rehab', NULL, 'no_show', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-03T11:00:00.000Z'::timestamptz),
  (11, 'RH-S1QY', 30, NULL, NULL, NULL, NULL, 1, 1, '2026-06-18T14:15:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Annual check', NULL, 'seen', 'phone', '2026-06-18T14:09:00.000Z'::timestamptz, '2026-06-18T14:17:00.000Z'::timestamptz, '2026-06-18T14:30:00.000Z'::timestamptz, NULL, FALSE, NULL, 6, NULL, 'Ivy Ferreira', NULL, NULL, '2026-06-08T13:25:00.000Z'::timestamptz),
  (12, 'RH-SFSW', 20, NULL, NULL, NULL, NULL, 2, 1, '2026-06-30T09:00:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Sick note', NULL, 'seen', 'online', '2026-06-30T08:54:00.000Z'::timestamptz, '2026-06-30T09:02:00.000Z'::timestamptz, '2026-06-30T09:15:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-25T20:15:00.000Z'::timestamptz),
  (13, 'RH-SV1D', 12, NULL, NULL, NULL, NULL, 3, 3, '2026-07-06T09:45:00.000Z'::timestamptz, 45, 60, 0, 60, 0, 'Knee follow-up', NULL, 'seen', 'phone', '2026-07-06T09:39:00.000Z'::timestamptz, '2026-07-06T09:47:00.000Z'::timestamptz, '2026-07-06T10:30:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-02T15:10:00.000Z'::timestamptz),
  (14, 'RH-SQBA', 19, NULL, NULL, NULL, NULL, 3, 3, '2026-07-08T13:00:00.000Z'::timestamptz, 45, 60, 0, 60, 0, 'Shoulder rehab', NULL, 'seen', 'online', '2026-07-08T12:54:00.000Z'::timestamptz, '2026-07-08T13:02:00.000Z'::timestamptz, '2026-07-08T13:45:00.000Z'::timestamptz, NULL, FALSE, NULL, 2, NULL, NULL, NULL, NULL, '2026-06-26T07:15:00.000Z'::timestamptz),
  (15, 'RH-S6NY', 24, NULL, NULL, NULL, NULL, 4, 4, '2026-07-09T08:15:00.000Z'::timestamptz, 15, 28, 0, 28, 0, 'Travel jabs', NULL, 'seen', 'phone', '2026-07-09T08:09:00.000Z'::timestamptz, '2026-07-09T08:17:00.000Z'::timestamptz, '2026-07-09T08:30:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-08T14:25:00.000Z'::timestamptz),
  (16, 'RH-S1VY', 21, NULL, NULL, NULL, NULL, 3, 3, '2026-07-13T14:30:00.000Z'::timestamptz, 45, 60, 0, 60, 0, 'Back follow-up', NULL, 'seen', 'phone', '2026-07-13T14:24:00.000Z'::timestamptz, '2026-07-13T14:32:00.000Z'::timestamptz, '2026-07-13T15:15:00.000Z'::timestamptz, NULL, FALSE, NULL, 2, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-07T08:10:00.000Z'::timestamptz),
  (17, 'RH-SG66', 18, NULL, NULL, NULL, NULL, 4, 4, '2026-07-14T09:00:00.000Z'::timestamptz, 15, 28, 28, 0, 0, 'Dressing change', NULL, 'seen', 'desk', '2026-07-14T08:54:00.000Z'::timestamptz, '2026-07-14T09:02:00.000Z'::timestamptz, '2026-07-14T09:15:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-03T11:55:00.000Z'::timestamptz),
  (18, 'RH-SKRK', 12, NULL, NULL, NULL, NULL, 3, 3, '2026-07-15T10:30:00.000Z'::timestamptz, 45, 60, 0, 38, 22, 'Knee follow-up', NULL, 'seen', 'phone', '2026-07-15T10:24:00.000Z'::timestamptz, '2026-07-15T10:32:00.000Z'::timestamptz, '2026-07-15T11:15:00.000Z'::timestamptz, NULL, FALSE, NULL, 4, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-03T09:55:00.000Z'::timestamptz),
  (19, 'RH-SDPR', 26, NULL, NULL, NULL, NULL, 2, 1, '2026-07-16T13:30:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'seen', 'online', '2026-07-16T13:24:00.000Z'::timestamptz, '2026-07-16T13:32:00.000Z'::timestamptz, '2026-07-16T13:45:00.000Z'::timestamptz, NULL, FALSE, NULL, 1, NULL, NULL, NULL, NULL, '2026-07-07T12:15:00.000Z'::timestamptz),
  (20, 'RH-SG0G', 13, NULL, NULL, NULL, NULL, 4, 4, '2026-07-17T08:45:00.000Z'::timestamptz, 15, 28, 0, 28, 0, 'Wound check', NULL, 'seen', 'phone', '2026-07-17T08:39:00.000Z'::timestamptz, '2026-07-17T08:47:00.000Z'::timestamptz, '2026-07-17T09:00:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-07T12:10:00.000Z'::timestamptz),
  (21, 'RH-SVX8', 20, NULL, NULL, NULL, NULL, 3, 3, '2026-07-20T15:15:00.000Z'::timestamptz, 45, 60, 15, 0, 45, 'First physio visit', NULL, 'seen', 'online', '2026-07-20T15:09:00.000Z'::timestamptz, '2026-07-20T15:17:00.000Z'::timestamptz, '2026-07-20T16:00:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-09T13:45:00.000Z'::timestamptz),
  (22, 'RH-SS5Y', 5, NULL, NULL, NULL, NULL, 1, 1, '2026-07-21T14:00:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Review appointment', NULL, 'seen', 'phone', '2026-07-21T13:54:00.000Z'::timestamptz, '2026-07-21T14:02:00.000Z'::timestamptz, '2026-07-21T14:15:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-09T11:55:00.000Z'::timestamptz),
  (23, 'RH-S7KC', 27, NULL, NULL, NULL, NULL, 1, 2, '2026-07-22T08:15:00.000Z'::timestamptz, 30, 70, 0, 35, 35, 'New patient registration', NULL, 'seen', 'online', '2026-07-22T08:09:00.000Z'::timestamptz, '2026-07-22T08:17:00.000Z'::timestamptz, '2026-07-22T08:45:00.000Z'::timestamptz, NULL, FALSE, NULL, 6, NULL, NULL, NULL, NULL, '2026-07-16T08:20:00.000Z'::timestamptz),
  (24, 'RH-SPCR', 22, NULL, NULL, NULL, NULL, 4, 4, '2026-07-23T10:30:00.000Z'::timestamptz, 15, 28, 0, 28, 0, 'Flu jab', NULL, 'seen', 'phone', '2026-07-23T10:24:00.000Z'::timestamptz, '2026-07-23T10:32:00.000Z'::timestamptz, '2026-07-23T10:45:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-13T07:40:00.000Z'::timestamptz),
  (25, 'RH-S577', 15, NULL, NULL, NULL, NULL, 1, 1, '2026-07-27T08:00:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Follow-up visit', NULL, 'seen', 'online', '2026-07-27T07:54:00.000Z'::timestamptz, '2026-07-27T08:02:00.000Z'::timestamptz, '2026-07-27T08:15:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-15T14:15:00.000Z'::timestamptz),
  (26, 'RH-SEDZ', 28, NULL, NULL, NULL, NULL, 2, 1, '2026-07-27T09:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Sick note', NULL, 'no_show', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-17T14:30:00.000Z'::timestamptz),
  (27, 'RH-SMT6', 31, NULL, NULL, NULL, NULL, 4, 4, '2026-07-27T10:00:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Flu jab', NULL, 'no_show', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-24T11:25:00.000Z'::timestamptz),
  (28, 'RH-SG0Z', 25, NULL, NULL, NULL, NULL, 1, 1, '2026-07-27T10:30:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Blood pressure check', NULL, 'seen', 'walk_in', '2026-07-27T10:24:00.000Z'::timestamptz, '2026-07-27T10:32:00.000Z'::timestamptz, '2026-07-27T10:45:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-27T10:10:00.000Z'::timestamptz),
  (29, 'RH-SSRB', 16, NULL, NULL, NULL, NULL, 2, 1, '2026-07-27T13:00:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Child check', NULL, 'seen', 'phone', '2026-07-27T12:54:00.000Z'::timestamptz, '2026-07-27T13:02:00.000Z'::timestamptz, '2026-07-27T13:15:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-21T10:40:00.000Z'::timestamptz),
  (30, 'RH-SJYC', 17, NULL, NULL, NULL, NULL, 2, 1, '2026-07-27T13:15:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Child check', NULL, 'seen', 'phone', '2026-07-27T13:09:00.000Z'::timestamptz, '2026-07-27T13:17:00.000Z'::timestamptz, '2026-07-27T13:30:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-21T08:55:00.000Z'::timestamptz),
  (31, 'RH-SN70', 1, NULL, NULL, NULL, NULL, 1, 1, '2026-07-28T07:30:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Annual check', NULL, 'seen', 'phone', '2026-07-28T07:30:00.000Z'::timestamptz, '2026-07-28T07:32:00.000Z'::timestamptz, '2026-07-28T07:45:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-23T12:10:00.000Z'::timestamptz),
  (32, 'RH-SSKP', 2, NULL, NULL, NULL, NULL, 2, 1, '2026-07-28T07:45:00.000Z'::timestamptz, 15, 45, 0, 45, 0, 'Sick note', NULL, 'seen', 'online', '2026-07-28T07:39:00.000Z'::timestamptz, '2026-07-28T07:47:00.000Z'::timestamptz, '2026-07-28T08:00:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-22T07:30:00.000Z'::timestamptz),
  (33, 'RH-SA00', 18, NULL, NULL, NULL, NULL, 4, 4, '2026-07-28T07:30:00.000Z'::timestamptz, 15, 28, 0, 28, 0, 'Dressing change', NULL, 'seen', 'recall', '2026-07-28T07:30:00.000Z'::timestamptz, '2026-07-28T07:32:00.000Z'::timestamptz, '2026-07-28T07:45:00.000Z'::timestamptz, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-24T07:55:00.000Z'::timestamptz),
  (34, 'RH-SXHV', 14, NULL, NULL, NULL, NULL, 4, 4, '2026-07-28T07:45:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Flu jab', 'Uses a wheelchair. Please keep the ground-floor room.', 'ready', 'phone', '2026-07-28T07:38:00.000Z'::timestamptz, '2026-07-28T07:46:00.000Z'::timestamptz, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-16T08:55:00.000Z'::timestamptz),
  (35, 'RH-STGT', 12, NULL, NULL, NULL, NULL, 3, 3, '2026-07-28T08:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Knee follow-up', NULL, 'roomed', 'phone', '2026-07-28T07:46:00.000Z'::timestamptz, '2026-07-28T08:02:00.000Z'::timestamptz, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-20T09:55:00.000Z'::timestamptz),
  (36, 'RH-SSJ9', 3, NULL, NULL, NULL, NULL, 1, 1, '2026-07-28T08:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-24T19:30:00.000Z'::timestamptz),
  (37, 'RH-SHF2', 8, NULL, NULL, NULL, NULL, 2, 1, '2026-07-28T08:15:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Annual check', NULL, 'with_clinician', 'phone', '2026-07-28T08:05:00.000Z'::timestamptz, '2026-07-28T08:14:00.000Z'::timestamptz, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-27T09:55:00.000Z'::timestamptz),
  (38, 'RH-S5YJ', 4, NULL, NULL, NULL, NULL, 1, 2, '2026-07-28T08:30:00.000Z'::timestamptz, 30, 70, 0, 0, 70, 'New patient registration', NULL, 'checked_in', 'online', '2026-07-28T08:12:00.000Z'::timestamptz, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-24T08:20:00.000Z'::timestamptz),
  (39, 'RH-S4X7', 9, NULL, NULL, NULL, NULL, 2, 1, '2026-07-28T08:45:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'booked', 'desk', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-23T14:10:00.000Z'::timestamptz),
  (40, 'RH-SQ6Y', 13, NULL, NULL, NULL, NULL, 4, 4, '2026-07-28T09:00:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Stitches out', 'Her father is bringing her.', 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-22T14:25:00.000Z'::timestamptz),
  (41, 'RH-SFSK', 19, NULL, NULL, NULL, NULL, 3, 3, '2026-07-28T09:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder rehab', NULL, 'booked', 'recall', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-27T07:55:00.000Z'::timestamptz),
  (42, 'RH-SBDQ', 5, NULL, NULL, NULL, NULL, 1, 1, '2026-07-28T09:15:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Review appointment', NULL, 'booked', 'recall', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-22T14:40:00.000Z'::timestamptz),
  (43, 'RH-S2V2', 10, NULL, NULL, NULL, NULL, 2, 2, '2026-07-28T09:30:00.000Z'::timestamptz, 30, 70, 0, 0, 70, 'New patient registration', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-25T08:20:00.000Z'::timestamptz),
  (44, 'RH-SAFS', 6, NULL, NULL, NULL, NULL, 1, 2, '2026-07-28T10:00:00.000Z'::timestamptz, 30, 70, 0, 0, 70, 'New patient registration', 'Coming straight from work, so may be a few minutes early.', 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-22T08:20:00.000Z'::timestamptz),
  (45, 'RH-SZM4', 21, NULL, NULL, NULL, NULL, 3, 3, '2026-07-28T10:15:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Back follow-up', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-22T11:40:00.000Z'::timestamptz),
  (46, 'RH-SRAG', 24, NULL, NULL, NULL, NULL, 4, 4, '2026-07-28T10:30:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Travel jabs', NULL, 'booked', 'waiting_list', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-22T13:25:00.000Z'::timestamptz),
  (47, 'RH-SA8Q', 11, NULL, NULL, NULL, NULL, 2, 1, '2026-07-28T12:30:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Review appointment', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-27T10:45:00.000Z'::timestamptz),
  (48, 'RH-S71K', 7, NULL, NULL, NULL, NULL, 1, 1, '2026-07-28T13:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Form to sign', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-24T10:10:00.000Z'::timestamptz),
  (49, 'RH-S880', 15, NULL, NULL, NULL, NULL, 3, 3, '2026-07-28T13:15:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Ankle rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-24T13:45:00.000Z'::timestamptz),
  (50, 'RH-S5ST', 29, NULL, NULL, NULL, NULL, 3, 3, '2026-07-27T14:30:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder rehab', NULL, 'cancelled', 'online', NULL, NULL, NULL, '2026-07-27T07:10:00.000Z'::timestamptz, TRUE, 'patient', NULL, NULL, NULL, NULL, NULL, '2026-07-20T18:30:00.000Z'::timestamptz),
  (51, 'RH-SY8M', 22, NULL, NULL, NULL, NULL, 1, 1, '2026-07-28T15:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Annual check', NULL, 'cancelled', 'phone', NULL, NULL, NULL, '2026-07-23T11:40:00.000Z'::timestamptz, FALSE, 'patient', NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-17T08:40:00.000Z'::timestamptz),
  (52, 'RH-SDA5', 30, NULL, NULL, NULL, NULL, 3, 3, '2026-07-28T14:15:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Back follow-up', NULL, 'cancelled', 'phone', NULL, NULL, NULL, '2026-07-28T06:35:00.000Z'::timestamptz, TRUE, 'patient', NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-17T15:25:00.000Z'::timestamptz),
  (53, 'RH-SMHG', 26, NULL, NULL, NULL, NULL, 1, 1, '2026-07-30T09:30:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'cancelled', 'online', NULL, NULL, NULL, '2026-07-28T07:40:00.000Z'::timestamptz, FALSE, 'desk', NULL, NULL, NULL, NULL, NULL, '2026-07-22T20:45:00.000Z'::timestamptz),
  (54, 'RH-ST7K', 20, NULL, NULL, NULL, NULL, 4, 4, '2026-07-29T08:15:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Travel jabs', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-17T07:00:00.000Z'::timestamptz),
  (55, 'RH-SH9F', 29, NULL, NULL, NULL, NULL, 1, 1, '2026-07-29T08:30:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Annual check', NULL, 'booked', 'recall', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-17T12:25:00.000Z'::timestamptz),
  (56, 'RH-S28J', 23, NULL, NULL, NULL, NULL, 2, 1, '2026-07-29T09:30:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Review appointment', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-17T08:10:00.000Z'::timestamptz),
  (57, 'RH-SZ2S', 22, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T07:30:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-27T06:00:00.000Z'::timestamptz),
  (58, 'RH-SBZY', 23, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T08:15:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Back follow-up', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-16T13:10:00.000Z'::timestamptz),
  (59, 'RH-SRG7', 26, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T09:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Knee follow-up', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-22T14:00:00.000Z'::timestamptz),
  (60, 'RH-S1X0', 27, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T09:45:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Ankle rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-22T08:45:00.000Z'::timestamptz),
  (61, 'RH-SGZD', 30, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T10:30:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Back follow-up', NULL, 'booked', 'desk', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-21T12:40:00.000Z'::timestamptz),
  (62, 'RH-SCYG', 29, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T12:15:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-20T16:30:00.000Z'::timestamptz),
  (63, 'RH-S45C', 25, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T13:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Knee follow-up', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-16T10:25:00.000Z'::timestamptz),
  (64, 'RH-SD5Z', 28, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T13:45:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Ankle rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-24T15:45:00.000Z'::timestamptz),
  (65, 'RH-SH00', 31, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T14:30:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Gait check', 'Her father is bringing her.', 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-22T08:25:00.000Z'::timestamptz),
  (66, 'RH-SGGJ', 19, NULL, NULL, NULL, NULL, 3, 3, '2026-07-29T15:15:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-27T17:15:00.000Z'::timestamptz),
  (67, 'RH-SMFS', 22, NULL, NULL, NULL, NULL, 1, 1, '2026-07-30T08:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Annual check', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-23T14:25:00.000Z'::timestamptz),
  (68, 'RH-S1NV', 20, NULL, NULL, NULL, NULL, 3, 3, '2026-07-30T09:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Knee rehab', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-20T11:45:00.000Z'::timestamptz),
  (69, 'RH-SMSE', 21, NULL, NULL, NULL, NULL, 4, 4, '2026-07-30T09:15:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Dressing change', NULL, 'booked', 'desk', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-24T09:25:00.000Z'::timestamptz),
  (70, 'RH-SNN6', 27, NULL, NULL, NULL, NULL, 2, 1, '2026-07-31T08:15:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Review appointment', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-23T10:45:00.000Z'::timestamptz),
  (71, 'RH-SNAC', 30, NULL, NULL, NULL, NULL, 1, 1, '2026-07-31T09:00:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'booked', 'recall', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-27T11:10:00.000Z'::timestamptz),
  (72, 'RH-S1QG', 1, NULL, NULL, NULL, NULL, 2, 1, '2026-08-03T08:30:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Blood pressure check', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-21T07:40:00.000Z'::timestamptz),
  (73, 'RH-SJ0D', 6, NULL, NULL, NULL, NULL, 4, 4, '2026-08-03T09:00:00.000Z'::timestamptz, 15, 28, 0, 0, 28, 'Travel jabs', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-27T12:30:00.000Z'::timestamptz),
  (74, 'RH-SMB1', 11, NULL, NULL, NULL, NULL, 1, 1, '2026-08-03T10:15:00.000Z'::timestamptz, 15, 45, 0, 0, 45, 'Follow-up visit', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-16T15:00:00.000Z'::timestamptz),
  (75, 'RH-S5CF', 8, NULL, NULL, NULL, NULL, 3, 3, '2026-08-03T13:00:00.000Z'::timestamptz, 45, 60, 0, 0, 60, 'Shoulder follow-up', NULL, 'booked', 'phone', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL, 'Ivy Ferreira', NULL, NULL, '2026-07-20T10:25:00.000Z'::timestamptz),
  (76, 'RH-S1JX', NULL, 'Léa Moreau', '2002-03-14', '07700 900203', NULL, 1, 2, '2026-07-31T08:15:00.000Z'::timestamptz, 30, 70, 0, 0, 70, 'New patient registration', NULL, 'booked', 'online', NULL, NULL, NULL, NULL, FALSE, NULL, NULL, 'fr-FR', NULL, 'to_check', NULL, '2026-07-28T06:40:00.000Z'::timestamptz);

INSERT INTO clinic_payments (id, appointment_id, amount, method, taken_by, paid_at, voided, void_reason, voided_by, client_key) VALUES
  (1, 1, 45, 'card', 'Callum Reid', '2026-01-13T10:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (2, 2, 45, 'card', 'Callum Reid', '2026-01-27T10:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (3, 3, 45, 'cash', 'Callum Reid', '2026-02-03T09:32:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (4, 4, 45, 'cash', 'Callum Reid', '2026-02-24T14:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (5, 6, 45, 'card', 'Callum Reid', '2026-04-28T08:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (6, 7, 28, 'cash', 'Callum Reid', '2026-05-05T10:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (7, 12, 45, 'card', 'Ivy Ferreira', '2026-06-30T09:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (8, 13, 60, 'card', 'Ivy Ferreira', '2026-07-06T10:32:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (9, 14, 60, 'card', 'Ivy Ferreira', '2026-07-08T13:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (10, 15, 28, 'card', 'Ivy Ferreira', '2026-07-09T08:32:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (11, 16, 60, 'card', 'Ivy Ferreira', '2026-07-13T15:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (12, 18, 38, 'card', 'Ivy Ferreira', '2026-07-15T11:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (13, 20, 28, 'card', 'Ivy Ferreira', '2026-07-17T09:02:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (14, 22, 45, 'card', 'Ivy Ferreira', '2026-07-21T14:17:00.000Z'::timestamptz, TRUE, 'Taken twice by mistake.', 'Ivy Ferreira', NULL),
  (15, 22, 45, 'card', 'Ivy Ferreira', '2026-07-21T14:20:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (16, 23, 35, 'card', 'Ivy Ferreira', '2026-07-22T08:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (17, 24, 28, 'card', 'Ivy Ferreira', '2026-07-23T10:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (18, 25, 45, 'card', 'Ivy Ferreira', '2026-07-27T08:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (19, 28, 45, 'cash', 'Ivy Ferreira', '2026-07-27T10:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (20, 29, 45, 'card', 'Ivy Ferreira', '2026-07-27T13:17:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (21, 30, 45, 'card', 'Ivy Ferreira', '2026-07-27T13:32:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (22, 31, 45, 'card', 'Ivy Ferreira', '2026-07-28T07:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (23, 32, 45, 'card', 'Ivy Ferreira', '2026-07-28T08:02:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL),
  (24, 33, 28, 'cash', 'Ivy Ferreira', '2026-07-28T07:47:00.000Z'::timestamptz, FALSE, NULL, NULL, NULL);

INSERT INTO clinic_write_offs (id, appointment_id, amount, reason, written_by, written_at, client_key) VALUES
  (1, 17, 28, 'Same wound as the week before — no second charge.', 'Ivy Ferreira', '2026-07-14T09:20:00.000Z'::timestamptz, NULL),
  (2, 21, 15, 'Student rate, agreed with Nadia.', 'Ivy Ferreira', '2026-07-20T16:05:00.000Z'::timestamptz, NULL);

INSERT INTO clinic_check_notes (id, registration_id, appointment_id, note, written_by, client_key, created_at) VALUES
  (1, 1, NULL, 'Left a message. Will try again tomorrow.', 'Ivy Ferreira', NULL, '2026-07-27T15:05:00.000Z'::timestamptz);

INSERT INTO clinic_recalls (id, patient_id, from_appointment_id, visit_type_id, clinician_id, client_key, weeks, due_on, status, reason, dismiss_reason, booked_appointment_id, created_at) VALUES
  (1, 14, 1, 1, 1, NULL, 24, '2026-06-30', 'due', 'Annual check', NULL, NULL, '2026-01-13T10:16:00.000Z'::timestamptz),
  (2, 29, 2, 1, 2, NULL, 28, '2026-08-11', 'booked', 'Review appointment', NULL, 55, '2026-01-27T10:46:00.000Z'::timestamptz),
  (3, 23, 3, 1, 1, NULL, 25, '2026-07-28', 'due', 'Annual check', NULL, NULL, '2026-02-03T09:31:00.000Z'::timestamptz),
  (4, 25, 4, 1, 2, NULL, 20, '2026-07-14', 'due', 'Follow-up visit', NULL, NULL, '2026-02-24T14:16:00.000Z'::timestamptz),
  (5, 1, 6, 1, 1, NULL, 52, '2027-04-27', 'due', 'Annual check', NULL, NULL, '2026-04-28T08:46:00.000Z'::timestamptz),
  (6, 18, 7, 4, 4, NULL, 12, '2026-07-28', 'booked', 'Dressing change', NULL, 33, '2026-05-05T10:16:00.000Z'::timestamptz),
  (7, 30, 11, 1, 1, NULL, 6, '2026-07-30', 'booked', 'Follow-up visit', NULL, 71, '2026-06-18T14:31:00.000Z'::timestamptz),
  (8, 19, 14, 3, 3, NULL, 2, '2026-07-22', 'booked', 'Shoulder rehab', NULL, 41, '2026-07-08T13:46:00.000Z'::timestamptz),
  (9, 21, 16, 3, 3, NULL, 2, '2026-07-27', 'booked', 'Back follow-up', NULL, 45, '2026-07-13T15:16:00.000Z'::timestamptz),
  (10, 26, 19, 1, 2, NULL, 1, '2026-07-23', 'noted', 'Follow-up visit', NULL, NULL, '2026-07-16T13:46:00.000Z'::timestamptz),
  (11, 27, 23, 1, 1, NULL, 6, '2026-09-02', 'due', 'Review appointment', NULL, NULL, '2026-07-22T08:46:00.000Z'::timestamptz),
  (12, 12, 18, 3, 3, NULL, 4, '2026-08-12', 'not_needed', 'Knee follow-up', 'Knee much better — will ring if it flares up.', NULL, '2026-07-15T11:16:00.000Z'::timestamptz);

INSERT INTO clinic_waiting_list (id, patient_id, visit_type_id, clinician_id, part_of_day, status, channel, booked_appointment_id, note, created_at) VALUES
  (1, 18, 4, 4, 'mornings', 'waiting', 'desk', NULL, 'Mornings only — she has a lift until noon.', '2026-07-21T08:20:00.000Z'::timestamptz),
  (2, 26, 1, NULL, 'any', 'waiting', 'online', NULL, 'Can come at short notice.', '2026-07-23T08:20:00.000Z'::timestamptz),
  (3, 24, 3, 3, 'afternoons', 'waiting', 'desk', NULL, NULL, '2026-07-24T08:20:00.000Z'::timestamptz),
  (4, 30, 1, 1, 'any', 'waiting', 'desk', NULL, NULL, '2026-07-26T08:20:00.000Z'::timestamptz),
  (5, 10, 2, NULL, 'mornings', 'waiting', 'online', NULL, NULL, '2026-07-27T08:20:00.000Z'::timestamptz);

INSERT INTO clinic_messages (id, kind, patient_id, appointment_id, recall_id, closure_id, to_address, language, status, error, due_at, sent_at, created_by, client_key, created_at) VALUES
  (1, 'confirmation', 20, 54, NULL, NULL, 'leila@example.com', 'en-US', 'sent', NULL, '2026-07-17T07:00:00.000Z'::timestamptz, '2026-07-17T07:00:00.000Z'::timestamptz, NULL, NULL, '2026-07-17T07:00:00.000Z'::timestamptz),
  (2, 'confirmation', 29, 55, NULL, NULL, 'clara@example.com', 'en-US', 'sent', NULL, '2026-07-17T12:25:00.000Z'::timestamptz, '2026-07-17T12:25:00.000Z'::timestamptz, NULL, NULL, '2026-07-17T12:25:00.000Z'::timestamptz),
  (3, 'confirmation', 23, 56, NULL, NULL, 'hamid@example.com', 'ar-EG', 'sent', NULL, '2026-07-17T08:10:00.000Z'::timestamptz, '2026-07-17T08:10:00.000Z'::timestamptz, NULL, NULL, '2026-07-17T08:10:00.000Z'::timestamptz),
  (4, 'confirmation', 27, 70, NULL, NULL, 'odette@example.com', 'fr-FR', 'sent', NULL, '2026-07-23T10:45:00.000Z'::timestamptz, '2026-07-23T10:45:00.000Z'::timestamptz, NULL, NULL, '2026-07-23T10:45:00.000Z'::timestamptz),
  (5, 'confirmation', 11, 74, NULL, NULL, 'priya@example.com', 'en-US', 'sent', NULL, '2026-07-16T15:00:00.000Z'::timestamptz, '2026-07-16T15:00:00.000Z'::timestamptz, NULL, NULL, '2026-07-16T15:00:00.000Z'::timestamptz),
  (6, 'reminder', 2, 32, NULL, NULL, 'ewan@example.com', 'en-US', 'sent', NULL, '2026-07-28T07:45:00.000Z'::timestamptz, '2026-07-27T07:45:00.000Z'::timestamptz, NULL, NULL, '2026-07-27T07:45:00.000Z'::timestamptz),
  (7, 'reminder', 13, 40, NULL, NULL, 'saoirse@example.com', 'en-US', 'sent', NULL, '2026-07-28T09:00:00.000Z'::timestamptz, '2026-07-27T09:00:00.000Z'::timestamptz, NULL, NULL, '2026-07-27T09:00:00.000Z'::timestamptz),
  (8, 'reminder', 5, 42, NULL, NULL, 'solveig@example.com', 'da-DK', 'sent', NULL, '2026-07-28T09:15:00.000Z'::timestamptz, '2026-07-27T09:15:00.000Z'::timestamptz, NULL, NULL, '2026-07-27T09:15:00.000Z'::timestamptz),
  (9, 'reminder', 7, 48, NULL, NULL, 'nour@example.com', 'ar-EG', 'sent', NULL, '2026-07-28T13:00:00.000Z'::timestamptz, '2026-07-27T13:00:00.000Z'::timestamptz, NULL, NULL, '2026-07-27T13:00:00.000Z'::timestamptz),
  (10, 'reminder', 10, 43, NULL, NULL, 'zofia@example.com', 'cs-CZ', 'failed', 'Not delivered: the mailbox is full.', '2026-07-28T09:30:00.000Z'::timestamptz, NULL, NULL, NULL, '2026-07-27T09:30:00.000Z'::timestamptz),
  (11, 'missed', 28, 26, NULL, NULL, 'yusuf@example.com', 'de-DE', 'sent', NULL, '2026-07-27T09:20:00.000Z'::timestamptz, '2026-07-27T09:20:00.000Z'::timestamptz, NULL, NULL, '2026-07-27T09:20:00.000Z'::timestamptz),
  (12, 'recall', 26, NULL, 10, NULL, 'bram@example.com', 'en-US', 'sent', NULL, '2026-07-24T10:05:00.000Z'::timestamptz, '2026-07-24T10:05:00.000Z'::timestamptz, 'Ivy Ferreira', NULL, '2026-07-24T10:05:00.000Z'::timestamptz),
  (13, 'confirmation', 6, 44, NULL, NULL, 'kofi@example.com', 'en-US', 'sent', NULL, '2026-07-22T08:20:00.000Z'::timestamptz, '2026-07-22T08:20:00.000Z'::timestamptz, NULL, NULL, '2026-07-22T08:20:00.000Z'::timestamptz);

INSERT INTO clinic_day_closes (id, day, no_shows_marked, cash_expected, cash_counted, note, closed_by, closed_at) VALUES
  (1, '2026-07-27', 2, 45, 45, 'All square. Card terminal batch sent at 17:35.', 'Ivy Ferreira', '2026-07-27T16:40:00.000Z'::timestamptz);

DO $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('clinic_settings', 'id'), (SELECT MAX(id) FROM clinic_settings));
  PERFORM setval(pg_get_serial_sequence('clinic_opening_hours', 'id'), (SELECT MAX(id) FROM clinic_opening_hours));
  PERFORM setval(pg_get_serial_sequence('clinic_clinicians', 'id'), (SELECT MAX(id) FROM clinic_clinicians));
  PERFORM setval(pg_get_serial_sequence('clinic_visit_types', 'id'), (SELECT MAX(id) FROM clinic_visit_types));
  PERFORM setval(pg_get_serial_sequence('clinic_clinician_visit_types', 'id'), (SELECT MAX(id) FROM clinic_clinician_visit_types));
  PERFORM setval(pg_get_serial_sequence('clinic_clinician_hours', 'id'), (SELECT MAX(id) FROM clinic_clinician_hours));
  PERFORM setval(pg_get_serial_sequence('clinic_closures', 'id'), (SELECT MAX(id) FROM clinic_closures));
  PERFORM setval(pg_get_serial_sequence('clinic_faqs', 'id'), (SELECT MAX(id) FROM clinic_faqs));
  PERFORM setval(pg_get_serial_sequence('clinic_patients', 'id'), (SELECT MAX(id) FROM clinic_patients));
  PERFORM setval(pg_get_serial_sequence('clinic_registrations', 'id'), (SELECT MAX(id) FROM clinic_registrations));
  PERFORM setval(pg_get_serial_sequence('clinic_appointments', 'id'), (SELECT MAX(id) FROM clinic_appointments));
  PERFORM setval(pg_get_serial_sequence('clinic_payments', 'id'), (SELECT MAX(id) FROM clinic_payments));
  PERFORM setval(pg_get_serial_sequence('clinic_write_offs', 'id'), (SELECT MAX(id) FROM clinic_write_offs));
  PERFORM setval(pg_get_serial_sequence('clinic_check_notes', 'id'), (SELECT MAX(id) FROM clinic_check_notes));
  PERFORM setval(pg_get_serial_sequence('clinic_recalls', 'id'), (SELECT MAX(id) FROM clinic_recalls));
  PERFORM setval(pg_get_serial_sequence('clinic_waiting_list', 'id'), (SELECT MAX(id) FROM clinic_waiting_list));
  PERFORM setval(pg_get_serial_sequence('clinic_messages', 'id'), (SELECT MAX(id) FROM clinic_messages));
  PERFORM setval(pg_get_serial_sequence('clinic_day_closes', 'id'), (SELECT MAX(id) FROM clinic_day_closes));
END
$$;

COMMIT;
