/**
 * The icons a toast can carry, by the lucide name the action passes
 * (`toast(text, { icon: "calendar-check" })`).
 *
 * Named one by one rather than importing lucide's whole set: that would put
 * some fifteen hundred icons into the desk's bundle for the thirty the toasts
 * use. A name not listed here draws the plain tick, so a new toast never
 * breaks — it only looks generic until its icon is added.
 */
import type { LucideIcon } from "lucide-react";
import {
  ArrowRightLeft,
  ArrowUpRight,
  BadgeCheck,
  BellOff,
  BellRing,
  CalendarCheck,
  CalendarCog,
  CalendarPlus,
  CalendarSync,
  CalendarX,
  Check,
  CheckCheck,
  CircleAlert,
  CircleCheck,
  Clock,
  DoorOpen,
  FastForward,
  FileMinus,
  HandHeart,
  Info,
  ListOrdered,
  LogIn,
  Mail,
  MailCheck,
  MailX,
  MoonStar,
  PhoneCall,
  Printer,
  Receipt,
  RotateCcw,
  Send,
  Timer,
  TriangleAlert,
  UserCheck,
  UserPlus,
  UserRoundCheck,
  UserRoundMinus,
  UserRoundX,
  Undo2,
  UserX,
  WifiOff,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "arrow-right-left": ArrowRightLeft,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  "calendar-check": CalendarCheck,
  "calendar-cog": CalendarCog,
  "calendar-plus": CalendarPlus,
  "calendar-sync": CalendarSync,
  "calendar-x": CalendarX,
  check: Check,
  "check-check": CheckCheck,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  clock: Clock,
  "door-open": DoorOpen,
  "fast-forward": FastForward,
  "file-minus": FileMinus,
  "hand-heart": HandHeart,
  info: Info,
  "list-ordered": ListOrdered,
  "log-in": LogIn,
  mail: Mail,
  "mail-x": MailX,
  "mail-check": MailCheck,
  "moon-star": MoonStar,
  "phone-call": PhoneCall,
  printer: Printer,
  receipt: Receipt,
  "rotate-ccw": RotateCcw,
  send: Send,
  timer: Timer,
  "triangle-alert": TriangleAlert,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-round-check": UserRoundCheck,
  "user-round-minus": UserRoundMinus,
  "user-round-x": UserRoundX,
  "undo-2": Undo2,
  "user-x": UserX,
  "wifi-off": WifiOff,
};

export const toastIcon = (name: string): LucideIcon => ICONS[name] ?? Check;
