/**
 * The stand-alone stack's SQL — `db/schema.sql` and `db/seed.sql` — written
 * from the two documents that already say it all: the manifest's tables and
 * the sample bundle. A `docker compose up` and an Adminium install therefore
 * create the same tables under the same names (`clinic_appointments`, …) and,
 * with sample data, the same practice.
 *
 * The seed is the bundle resolved once, at the moment the design is drawn —
 * Tuesday 28 July 2026, 09:20 in London — by the same resolver the website's
 * demo runs (`sampleRows.ts`): the ids, the statuses that follow the clock,
 * the copied fees and the settled balances are all what an install made at
 * that moment would hold. A database loaded from it is that Tuesday morning,
 * whenever it is loaded; the words are the English ones.
 *
 * PostgreSQL only (the compose stack's database). Pure: text in, text out —
 * `db/write-sample.ts` writes the files, sample-drift.test.ts compares them.
 */
import { SAMPLE_MOMENT, SAMPLE_ZONE, type SampleBundle } from "./sample.ts";
import { resolveSample } from "./sampleRows.ts";

interface Column {
  ref: string;
  type: string;
  role?: string;
  nullable?: boolean;
  references?: string;
  enum?: string[];
  default?: string | number | boolean;
  maxLength?: number;
  unique?: boolean;
  rules?: Record<string, unknown>;
}
interface Table {
  ref: string;
  columns: Column[];
}
export interface ManifestTables {
  key: string;
  requiredSchema: { prefixed?: boolean; tables: Table[] };
}

/** The names an Adminium install gives the tables: the app's key, then the table. */
const realName = (manifest: ManifestTables, ref: string) => (manifest.requiredSchema.prefixed === true ? `${manifest.key.replace(/-/g, "_")}_${ref}` : ref);
const quote = (text: string) => `'${text.replace(/'/g, "''")}'`;

/** Parents before the tables that point at them. */
function creationOrder(tables: Table[]): Table[] {
  const byRef = new Map(tables.map((t) => [t.ref, t]));
  const done = new Set<string>();
  const out: Table[] = [];
  const visit = (table: Table, path: Set<string>) => {
    if (done.has(table.ref)) return;
    if (path.has(table.ref)) throw new Error(`the tables point at each other in a cycle through "${table.ref}"`);
    path.add(table.ref);
    for (const column of table.columns) {
      if (column.type !== "fk" || column.references === undefined || column.references === table.ref) continue;
      visit(byRef.get(column.references)!, path);
    }
    path.delete(table.ref);
    done.add(table.ref);
    out.push(table);
  };
  for (const table of tables) visit(table, new Set());
  return out;
}

function columnSql(manifest: ManifestTables, column: Column): string {
  if (column.role === "pk") return `${column.ref} SERIAL PRIMARY KEY`;
  let type: string;
  switch (column.type) {
    case "text":
      type = column.maxLength === undefined ? "TEXT" : `VARCHAR(${String(column.maxLength)})`;
      break;
    case "int":
    case "fk":
      type = "INTEGER";
      break;
    case "money":
      type = "NUMERIC(12, 2)";
      break;
    case "bool":
      type = "BOOLEAN";
      break;
    case "enum":
      type = "TEXT";
      break;
    case "date":
      type = "DATE";
      break;
    case "timestamptz":
      type = "TIMESTAMPTZ";
      break;
    default:
      throw new Error(`no SQL type for manifest type "${column.type}" (${column.ref})`);
  }
  const parts = [column.ref, type];
  if (column.nullable !== true) parts.push("NOT NULL");
  if (column.default !== undefined) {
    const value = column.default;
    parts.push(
      `DEFAULT ${value === "now" && column.type === "timestamptz" ? "now()" : typeof value === "string" ? quote(value) : typeof value === "boolean" ? (value ? "TRUE" : "FALSE") : String(value)}`,
    );
  }
  if (column.type === "enum") parts.push(`CHECK (${column.ref} IN (${(column.enum ?? []).map(quote).join(", ")}))`);
  if (column.type === "fk") parts.push(`REFERENCES ${realName(manifest, column.references!)} (id)`);
  // A reference a patient reads out, a number from a counter, and a column the manifest marks unique are each unique.
  if (column.unique === true || column.rules?.["code"] !== undefined || column.rules?.["sequence"] !== undefined) parts.push("UNIQUE");
  return parts.join(" ");
}

export function schemaSql(manifest: ManifestTables): string {
  const tables = creationOrder(manifest.requiredSchema.tables);
  const out: string[] = [
    "-- Clinic Desk — the PostgreSQL schema of the stand-alone stack.",
    "--",
    "-- GENERATED by `npm run sample` (db/write-sample.ts) from manifest.json, so a",
    "-- compose install and an Adminium install create the same tables. Do not edit",
    "-- by hand: change the manifest and regenerate. src/data/sample-drift.test.ts",
    "-- fails when this file and the manifest disagree.",
    "",
    ...[...tables].reverse().map((t) => `DROP TABLE IF EXISTS ${realName(manifest, t.ref)} CASCADE;`),
    "",
  ];
  for (const table of tables) {
    out.push(`CREATE TABLE ${realName(manifest, table.ref)} (`);
    out.push(table.columns.map((column) => `  ${columnSql(manifest, column)}`).join(",\n"));
    out.push(");", "");
  }
  for (const table of tables) {
    for (const column of table.columns) {
      if (column.type !== "fk") continue;
      out.push(`CREATE INDEX idx_${table.ref}_${column.ref} ON ${realName(manifest, table.ref)} (${column.ref});`);
    }
  }
  return `${out.join("\n")}\n`;
}

// ── seed.sql ────────────────────────────────────────────────────────────────

export function seedSql(bundle: SampleBundle, manifest: ManifestTables): string {
  const tables = new Map(manifest.requiredSchema.tables.map((t) => [t.ref, t]));
  const rows = resolveSample(bundle, { now: SAMPLE_MOMENT, zone: SAMPLE_ZONE, locale: "en-US" });
  const out: string[] = [
    "-- Clinic Desk — the stand-alone stack's sample practice.",
    "--",
    "-- GENERATED by `npm run sample` (db/write-sample.ts) from the same bundle an",
    "-- operator adds from Adminium (seeds/clinic.sample.json), resolved at the",
    "-- moment the design is drawn: Tuesday 28 July 2026, 09:20 in London. Loaded",
    "-- at any time, the database is that morning; the words are the English ones.",
    "-- Do not edit by hand.",
    "",
    "BEGIN;",
    "",
  ];
  const literal = (value: unknown, column: Column): string => {
    if (value === null || value === undefined) return "NULL";
    if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
    if (typeof value === "number") return String(value);
    if (typeof value === "string") return column.type === "timestamptz" ? `${quote(value)}::timestamptz` : quote(value);
    throw new Error(`cannot write ${JSON.stringify(value)} into ${column.ref}`);
  };
  const written: string[] = [];
  for (const { ref } of bundle.tables) {
    const table = tables.get(ref);
    if (table === undefined) throw new Error(`"${ref}" is not a table of the manifest`);
    const list = rows[ref] ?? [];
    if (list.length === 0) continue;
    written.push(ref);
    out.push(`INSERT INTO ${realName(manifest, ref)} (${table.columns.map((c) => c.ref).join(", ")}) VALUES`);
    out.push(`${list.map((row) => `  (${table.columns.map((c) => literal(row[c.ref], c)).join(", ")})`).join(",\n")};`, "");
  }
  // The keys were written by hand above: move each counter past them.
  out.push("DO $$", "BEGIN");
  for (const ref of written) {
    out.push(`  PERFORM setval(pg_get_serial_sequence('${realName(manifest, ref)}', 'id'), (SELECT MAX(id) FROM ${realName(manifest, ref)}));`);
  }
  out.push("END", "$$;", "", "COMMIT;");
  return `${out.join("\n")}\n`;
}
